/***************************************************************************
								TIED SOFTWARE
 PROJECT	:- TS3000

 MODULE 	:- GLOBALH

 FILE 		:- NVRAM.H

 PROGRAMMER :- R Cockerell

 Copyright 1994. The University of Newcastle Research Associates Ltd.

****************************************************************************
* POLYTRON VERSION CONTROL SOFTWARE _ PVCS (tm) Information
*
*      $Revision:   1.1.1.0  $
*      $Date:   29 Apr 1994 19:41:10  $
*
****************************************************************************/

/****************************************************************************
* This file contains definitions required by "NVRAM.C".
*
*****************************************************************************/

#ifndef __NVRAM_H
#define __NVRAM_H

#define	NVRAM_BASE_ADDR 0xD0000000UL       /* Absolute address D000:0000 */
#define NVRAM_SIZE		0x8000U /* should be 0xFFFF */

#endif	/* __NVRAM_H */

/*** End of NVRAM.H *********************************************************/