/*****************************************************************************
* POLYTRON VERSION CONTROL SOFTWARE _ PVCS (tm) Header Information
*
* 	$Revision:   2.6  $
*	$Date:   06 Mar 1992 18:04:44  $
*
*****************************************************************************/
/*


				INCLUDE FILE FOR PARSER SCREEN ROUTINE

					Should be included by Screen task (screen.c)

*/

extern void display_parser ( void );
