/************************************************************************/
/*                                                                      */
/*                                                                      */
/*                                                                      */
/*                SERIAL DEVICE DRIVER INITIALISATION HEADER			*/
/*									FILE 					            */
/*                                                                      */
/*                                   by                                 */
/*                                                                      */
/*                               Robert Betz                            */
/*            Department of Electrical and Computer Engineering         */
/*                          University of Newcastle                     */
/*                    (Copyright 1988, 1989, 1990, 1992)                */
/*                                                                      */
/*                                                                      */
/*                                                                      */
/************************************************************************/



extern int fintSerialChannelInitialise (void);
