c:\unimel\kalman\kaltest.c 1: 
c:\unimel\kalman\kaltest.c 2: 
c:\unimel\kalman\kaltest.c 3: 
H:\BC4\INCLUDE\stdio.h 1: 
H:\BC4\INCLUDE\stdio.h 2: 
H:\BC4\INCLUDE\stdio.h 3: 
H:\BC4\INCLUDE\stdio.h 4: 
H:\BC4\INCLUDE\stdio.h 5: 
H:\BC4\INCLUDE\stdio.h 6: 
H:\BC4\INCLUDE\stdio.h 7: 
H:\BC4\INCLUDE\stdio.h 8: 
H:\BC4\INCLUDE\stdio.h 9: 
H:\BC4\INCLUDE\stdio.h 10: 
H:\BC4\INCLUDE\stdio.h 11: 
H:\BC4\INCLUDE\stdio.h 12: 
H:\BC4\INCLUDE\stdio.h 13: 
H:\BC4\INCLUDE\stdio.h 14: 
H:\BC4\INCLUDE\stdio.h 15: 
H:\BC4\INCLUDE\stdio.h 16: 
H:\BC4\INCLUDE\stdio.h 17: 
H:\BC4\INCLUDE\stdio.h 18: 
H:\BC4\INCLUDE\stdio.h 19: 
H:\BC4\INCLUDE\_defs.h 1: 
H:\BC4\INCLUDE\_defs.h 2: 
H:\BC4\INCLUDE\_defs.h 3: 
H:\BC4\INCLUDE\_defs.h 4: 
H:\BC4\INCLUDE\_defs.h 5: 
H:\BC4\INCLUDE\_defs.h 6: 
H:\BC4\INCLUDE\_defs.h 7: 
H:\BC4\INCLUDE\_defs.h 8: 
H:\BC4\INCLUDE\_defs.h 9: 
H:\BC4\INCLUDE\_defs.h 10: 
H:\BC4\INCLUDE\_defs.h 11: 
H:\BC4\INCLUDE\_defs.h 12: 
H:\BC4\INCLUDE\_defs.h 13: 
H:\BC4\INCLUDE\_defs.h 14: 
H:\BC4\INCLUDE\_defs.h 15: 
H:\BC4\INCLUDE\_defs.h 16: 
H:\BC4\INCLUDE\_defs.h 17: 
H:\BC4\INCLUDE\_defs.h 18: 
H:\BC4\INCLUDE\_defs.h 19: 
H:\BC4\INCLUDE\_defs.h 20: 
H:\BC4\INCLUDE\_defs.h 21: 
H:\BC4\INCLUDE\_defs.h 22: 
H:\BC4\INCLUDE\_defs.h 23: 
H:\BC4\INCLUDE\_defs.h 24: 
H:\BC4\INCLUDE\_defs.h 25: 
H:\BC4\INCLUDE\_defs.h 26: 
H:\BC4\INCLUDE\_defs.h 27: 
H:\BC4\INCLUDE\_defs.h 28: 
H:\BC4\INCLUDE\_defs.h 29: 
H:\BC4\INCLUDE\_defs.h 30: 
H:\BC4\INCLUDE\_defs.h 31: 
H:\BC4\INCLUDE\_defs.h 32: 
H:\BC4\INCLUDE\_defs.h 33: 
H:\BC4\INCLUDE\_defs.h 34: 
H:\BC4\INCLUDE\_defs.h 35: 
H:\BC4\INCLUDE\_defs.h 36: 
H:\BC4\INCLUDE\_defs.h 37: 
H:\BC4\INCLUDE\_defs.h 38: 
H:\BC4\INCLUDE\_defs.h 39: 
H:\BC4\INCLUDE\_defs.h 40: 
H:\BC4\INCLUDE\_defs.h 41: 
H:\BC4\INCLUDE\_defs.h 42: 
H:\BC4\INCLUDE\_defs.h 43: 
H:\BC4\INCLUDE\_defs.h 44: 
H:\BC4\INCLUDE\_defs.h 45: 
H:\BC4\INCLUDE\_defs.h 46: 
H:\BC4\INCLUDE\_defs.h 47: 
H:\BC4\INCLUDE\_defs.h 48: 
H:\BC4\INCLUDE\_defs.h 49: 
H:\BC4\INCLUDE\_defs.h 50: 
H:\BC4\INCLUDE\_defs.h 51: 
H:\BC4\INCLUDE\_defs.h 52: 
H:\BC4\INCLUDE\_defs.h 53: 
H:\BC4\INCLUDE\_defs.h 54: 
H:\BC4\INCLUDE\_defs.h 55: 
H:\BC4\INCLUDE\_defs.h 56: 
H:\BC4\INCLUDE\_defs.h 57: 
H:\BC4\INCLUDE\_defs.h 58: 
H:\BC4\INCLUDE\_defs.h 59: 
H:\BC4\INCLUDE\_defs.h 60: 
H:\BC4\INCLUDE\_defs.h 61: 
H:\BC4\INCLUDE\_defs.h 62: 
H:\BC4\INCLUDE\_defs.h 63: 
H:\BC4\INCLUDE\_defs.h 64: 
H:\BC4\INCLUDE\_defs.h 65: 
H:\BC4\INCLUDE\_defs.h 66: 
H:\BC4\INCLUDE\_defs.h 67: 
H:\BC4\INCLUDE\_defs.h 68: 
H:\BC4\INCLUDE\_defs.h 69: 
H:\BC4\INCLUDE\_defs.h 70: 
H:\BC4\INCLUDE\_defs.h 71: 
H:\BC4\INCLUDE\_defs.h 72: 
H:\BC4\INCLUDE\_defs.h 73: 
H:\BC4\INCLUDE\_defs.h 74: 
H:\BC4\INCLUDE\_defs.h 75: 
H:\BC4\INCLUDE\_defs.h 76: 
H:\BC4\INCLUDE\_defs.h 77: 
H:\BC4\INCLUDE\_defs.h 78: 
H:\BC4\INCLUDE\_defs.h 79: 
H:\BC4\INCLUDE\_defs.h 80: 
H:\BC4\INCLUDE\_defs.h 81:   
H:\BC4\INCLUDE\_defs.h 82: 
H:\BC4\INCLUDE\_defs.h 83: 
H:\BC4\INCLUDE\_defs.h 84: 
H:\BC4\INCLUDE\_defs.h 85:     
H:\BC4\INCLUDE\_defs.h 86: 
H:\BC4\INCLUDE\_defs.h 87: 
H:\BC4\INCLUDE\_defs.h 88: 
H:\BC4\INCLUDE\_defs.h 89: 
H:\BC4\INCLUDE\_defs.h 90: 
H:\BC4\INCLUDE\_defs.h 91: 
H:\BC4\INCLUDE\_defs.h 92: 
H:\BC4\INCLUDE\_defs.h 93: 
H:\BC4\INCLUDE\_defs.h 94: 
H:\BC4\INCLUDE\_defs.h 95: 
H:\BC4\INCLUDE\_defs.h 96: 
H:\BC4\INCLUDE\_defs.h 97: 
H:\BC4\INCLUDE\_defs.h 98: 
H:\BC4\INCLUDE\_defs.h 99: 
H:\BC4\INCLUDE\_defs.h 100: 
H:\BC4\INCLUDE\_defs.h 101: 
H:\BC4\INCLUDE\_defs.h 102: 
H:\BC4\INCLUDE\_defs.h 103: 
H:\BC4\INCLUDE\_defs.h 104: 
H:\BC4\INCLUDE\_defs.h 105:   
H:\BC4\INCLUDE\_defs.h 106: 
H:\BC4\INCLUDE\_defs.h 107: 
H:\BC4\INCLUDE\_defs.h 108: 
H:\BC4\INCLUDE\_defs.h 109: 
H:\BC4\INCLUDE\_defs.h 110: 
H:\BC4\INCLUDE\_defs.h 111: 
H:\BC4\INCLUDE\_defs.h 112: 
H:\BC4\INCLUDE\_defs.h 113: 
H:\BC4\INCLUDE\_defs.h 114: 
H:\BC4\INCLUDE\_defs.h 115: 
H:\BC4\INCLUDE\_defs.h 116: 
H:\BC4\INCLUDE\_defs.h 117: 
H:\BC4\INCLUDE\_defs.h 118: 
H:\BC4\INCLUDE\_defs.h 119: 
H:\BC4\INCLUDE\_defs.h 120: 
H:\BC4\INCLUDE\_defs.h 121: 
H:\BC4\INCLUDE\_defs.h 122: 
H:\BC4\INCLUDE\_defs.h 123: 
H:\BC4\INCLUDE\_defs.h 124: 
H:\BC4\INCLUDE\_defs.h 125: 
H:\BC4\INCLUDE\_defs.h 126: 
H:\BC4\INCLUDE\_defs.h 127: 
H:\BC4\INCLUDE\_defs.h 128: 
H:\BC4\INCLUDE\_defs.h 129: 
H:\BC4\INCLUDE\_defs.h 130: 
H:\BC4\INCLUDE\_defs.h 131: 
H:\BC4\INCLUDE\_defs.h 132: 
H:\BC4\INCLUDE\_defs.h 133: 
H:\BC4\INCLUDE\_defs.h 134:   
H:\BC4\INCLUDE\_defs.h 135: 
H:\BC4\INCLUDE\_defs.h 136: 
H:\BC4\INCLUDE\_defs.h 137: 
H:\BC4\INCLUDE\_defs.h 138: 
H:\BC4\INCLUDE\_defs.h 139: 
H:\BC4\INCLUDE\_defs.h 140: 
H:\BC4\INCLUDE\_defs.h 141: 
H:\BC4\INCLUDE\_defs.h 142: 
H:\BC4\INCLUDE\_defs.h 143: 
H:\BC4\INCLUDE\_defs.h 144: 
H:\BC4\INCLUDE\_defs.h 145: 
H:\BC4\INCLUDE\_defs.h 146: 
H:\BC4\INCLUDE\_defs.h 147: 
H:\BC4\INCLUDE\_defs.h 148: 
H:\BC4\INCLUDE\_defs.h 149: 
H:\BC4\INCLUDE\_defs.h 150: 
H:\BC4\INCLUDE\_defs.h 151: 
H:\BC4\INCLUDE\_defs.h 152: 
H:\BC4\INCLUDE\_defs.h 153: 
H:\BC4\INCLUDE\_defs.h 154: 
H:\BC4\INCLUDE\_defs.h 155: 
H:\BC4\INCLUDE\_defs.h 156: 
H:\BC4\INCLUDE\_defs.h 157: 
H:\BC4\INCLUDE\_defs.h 158: 
H:\BC4\INCLUDE\_defs.h 159: 
H:\BC4\INCLUDE\_defs.h 160: 
H:\BC4\INCLUDE\_defs.h 161: 
H:\BC4\INCLUDE\_defs.h 162: 
H:\BC4\INCLUDE\_defs.h 163: 
H:\BC4\INCLUDE\_defs.h 164: 
H:\BC4\INCLUDE\_defs.h 165: 
H:\BC4\INCLUDE\_defs.h 166: 
H:\BC4\INCLUDE\_defs.h 167: 
H:\BC4\INCLUDE\_defs.h 168: 
H:\BC4\INCLUDE\_defs.h 169: 
H:\BC4\INCLUDE\_defs.h 170: 
H:\BC4\INCLUDE\_defs.h 171: 
H:\BC4\INCLUDE\_defs.h 172: 
H:\BC4\INCLUDE\_defs.h 173: 
H:\BC4\INCLUDE\stdio.h 20: 
H:\BC4\INCLUDE\stdio.h 21: 
H:\BC4\INCLUDE\stdio.h 22: 
H:\BC4\INCLUDE\stdio.h 23: 
H:\BC4\INCLUDE\_nfile.h 1: 
H:\BC4\INCLUDE\_nfile.h 2: 
H:\BC4\INCLUDE\_nfile.h 3: 
H:\BC4\INCLUDE\_nfile.h 4: 
H:\BC4\INCLUDE\_nfile.h 5: 
H:\BC4\INCLUDE\_nfile.h 6: 
H:\BC4\INCLUDE\_nfile.h 7: 
H:\BC4\INCLUDE\_nfile.h 8: 
H:\BC4\INCLUDE\_nfile.h 9: 
H:\BC4\INCLUDE\_nfile.h 10: 
H:\BC4\INCLUDE\_nfile.h 11: 
H:\BC4\INCLUDE\_nfile.h 12: 
H:\BC4\INCLUDE\_nfile.h 13: 
H:\BC4\INCLUDE\_nfile.h 14: 
H:\BC4\INCLUDE\_nfile.h 15: 
H:\BC4\INCLUDE\_nfile.h 16: 
H:\BC4\INCLUDE\_nfile.h 17: 
H:\BC4\INCLUDE\_nfile.h 18: 
H:\BC4\INCLUDE\_nfile.h 19: 
H:\BC4\INCLUDE\_nfile.h 20: 
H:\BC4\INCLUDE\_nfile.h 21: 
H:\BC4\INCLUDE\_nfile.h 22: 
H:\BC4\INCLUDE\_nfile.h 23: 
H:\BC4\INCLUDE\_nfile.h 24: 
H:\BC4\INCLUDE\_nfile.h 25: 
H:\BC4\INCLUDE\_nfile.h 26: 
H:\BC4\INCLUDE\_nfile.h 27: 
H:\BC4\INCLUDE\_nfile.h 28: 
H:\BC4\INCLUDE\_nfile.h 29: 
H:\BC4\INCLUDE\_nfile.h 30: 
H:\BC4\INCLUDE\stdio.h 24: 
H:\BC4\INCLUDE\stdio.h 25: 
H:\BC4\INCLUDE\stdio.h 26: 
H:\BC4\INCLUDE\stdio.h 27: 
H:\BC4\INCLUDE\_null.h 1: 
H:\BC4\INCLUDE\_null.h 2: 
H:\BC4\INCLUDE\_null.h 3: 
H:\BC4\INCLUDE\_null.h 4: 
H:\BC4\INCLUDE\_null.h 5: 
H:\BC4\INCLUDE\_null.h 6: 
H:\BC4\INCLUDE\_null.h 7: 
H:\BC4\INCLUDE\_null.h 8: 
H:\BC4\INCLUDE\_null.h 9: 
H:\BC4\INCLUDE\_null.h 10: 
H:\BC4\INCLUDE\_null.h 11: 
H:\BC4\INCLUDE\_null.h 12: 
H:\BC4\INCLUDE\_null.h 13: 
H:\BC4\INCLUDE\_null.h 14: 
H:\BC4\INCLUDE\_null.h 15: 
H:\BC4\INCLUDE\_null.h 16: 
H:\BC4\INCLUDE\_null.h 17:     
H:\BC4\INCLUDE\_null.h 18: 
H:\BC4\INCLUDE\_null.h 19: 
H:\BC4\INCLUDE\_null.h 20: 
H:\BC4\INCLUDE\_null.h 21: 
H:\BC4\INCLUDE\_null.h 22: 
H:\BC4\INCLUDE\_null.h 23: 
H:\BC4\INCLUDE\_null.h 24: 
H:\BC4\INCLUDE\_null.h 25: 
H:\BC4\INCLUDE\_null.h 26: 
H:\BC4\INCLUDE\_null.h 27: 
H:\BC4\INCLUDE\_null.h 28: 
H:\BC4\INCLUDE\_null.h 29: 
H:\BC4\INCLUDE\_null.h 30: 
H:\BC4\INCLUDE\_null.h 31: 
H:\BC4\INCLUDE\_null.h 32: 
H:\BC4\INCLUDE\stdio.h 28: 
H:\BC4\INCLUDE\stdio.h 29: 
H:\BC4\INCLUDE\stdio.h 30: 
H:\BC4\INCLUDE\stdio.h 31: #pragma option -a-
H:\BC4\INCLUDE\stdio.h 32: 
H:\BC4\INCLUDE\stdio.h 33: 
H:\BC4\INCLUDE\stdio.h 34: 
H:\BC4\INCLUDE\stdio.h 35: 
H:\BC4\INCLUDE\stdio.h 36: typedef unsigned size_t;
H:\BC4\INCLUDE\stdio.h 37: 
H:\BC4\INCLUDE\stdio.h 38: 
H:\BC4\INCLUDE\stdio.h 39: 
H:\BC4\INCLUDE\stdio.h 40: 
H:\BC4\INCLUDE\stdio.h 41: typedef long    fpos_t;
H:\BC4\INCLUDE\stdio.h 42: 
H:\BC4\INCLUDE\stdio.h 43: 
H:\BC4\INCLUDE\stdio.h 44: 
H:\BC4\INCLUDE\stdio.h 45: 
H:\BC4\INCLUDE\stdio.h 46: extern int _floatconvert;
H:\BC4\INCLUDE\stdio.h 47: 
H:\BC4\INCLUDE\stdio.h 48: 
H:\BC4\INCLUDE\stdio.h 49: 
H:\BC4\INCLUDE\stdio.h 50: 
H:\BC4\INCLUDE\stdio.h 51: 
H:\BC4\INCLUDE\stdio.h 52: 
H:\BC4\INCLUDE\stdio.h 53: 
H:\BC4\INCLUDE\stdio.h 54: 
H:\BC4\INCLUDE\stdio.h 55: 
H:\BC4\INCLUDE\stdio.h 56: 
H:\BC4\INCLUDE\stdio.h 57: 
H:\BC4\INCLUDE\stdio.h 58: 
H:\BC4\INCLUDE\stdio.h 59: 
H:\BC4\INCLUDE\stdio.h 60: 
H:\BC4\INCLUDE\stdio.h 61: 
H:\BC4\INCLUDE\stdio.h 62: 
H:\BC4\INCLUDE\stdio.h 63: 
H:\BC4\INCLUDE\stdio.h 64: 
H:\BC4\INCLUDE\stdio.h 65: 
H:\BC4\INCLUDE\stdio.h 66: 
H:\BC4\INCLUDE\stdio.h 67: 
H:\BC4\INCLUDE\stdio.h 68: 
H:\BC4\INCLUDE\stdio.h 69: 
H:\BC4\INCLUDE\stdio.h 70: 
H:\BC4\INCLUDE\stdio.h 71: 
H:\BC4\INCLUDE\stdio.h 72: 
H:\BC4\INCLUDE\stdio.h 73: 
H:\BC4\INCLUDE\stdio.h 74: 
H:\BC4\INCLUDE\stdio.h 75: 
H:\BC4\INCLUDE\stdio.h 76: 
H:\BC4\INCLUDE\stdio.h 77: 
H:\BC4\INCLUDE\stdio.h 78: 
H:\BC4\INCLUDE\stdio.h 79: 
H:\BC4\INCLUDE\stdio.h 80: 
H:\BC4\INCLUDE\stdio.h 81: 
H:\BC4\INCLUDE\stdio.h 82: 
H:\BC4\INCLUDE\stdio.h 83: 
H:\BC4\INCLUDE\stdio.h 84: 
H:\BC4\INCLUDE\stdio.h 85: 
H:\BC4\INCLUDE\stdio.h 86: 
H:\BC4\INCLUDE\stdio.h 87: 
H:\BC4\INCLUDE\stdio.h 88: 
H:\BC4\INCLUDE\stdio.h 89: 
H:\BC4\INCLUDE\stdio.h 90: 
H:\BC4\INCLUDE\stdio.h 91: 
H:\BC4\INCLUDE\stdio.h 92: 
H:\BC4\INCLUDE\stdio.h 93: 
H:\BC4\INCLUDE\stdio.h 94: 
H:\BC4\INCLUDE\stdio.h 95: 
H:\BC4\INCLUDE\stdio.h 96: 
H:\BC4\INCLUDE\stdio.h 97: typedef struct  {
H:\BC4\INCLUDE\stdio.h 98: int             level;          
H:\BC4\INCLUDE\stdio.h 99: unsigned        flags;          
H:\BC4\INCLUDE\stdio.h 100: char            fd;             
H:\BC4\INCLUDE\stdio.h 101: unsigned char   hold;           
H:\BC4\INCLUDE\stdio.h 102: int             bsize;          
H:\BC4\INCLUDE\stdio.h 103: unsigned char    *buffer;   
H:\BC4\INCLUDE\stdio.h 104: unsigned char    *curp;     
H:\BC4\INCLUDE\stdio.h 105: unsigned        istemp;         
H:\BC4\INCLUDE\stdio.h 106: short           token;          
H:\BC4\INCLUDE\stdio.h 107: }       FILE;                           
H:\BC4\INCLUDE\stdio.h 108: 
H:\BC4\INCLUDE\stdio.h 109: 
H:\BC4\INCLUDE\stdio.h 110: 
H:\BC4\INCLUDE\stdio.h 111: 
H:\BC4\INCLUDE\stdio.h 112: 
H:\BC4\INCLUDE\stdio.h 113: 
H:\BC4\INCLUDE\stdio.h 114: 
H:\BC4\INCLUDE\stdio.h 115: 
H:\BC4\INCLUDE\stdio.h 116: 
H:\BC4\INCLUDE\stdio.h 117: 
H:\BC4\INCLUDE\stdio.h 118: 
H:\BC4\INCLUDE\stdio.h 119: 
H:\BC4\INCLUDE\stdio.h 120: 
H:\BC4\INCLUDE\stdio.h 121: 
H:\BC4\INCLUDE\stdio.h 122: 
H:\BC4\INCLUDE\stdio.h 123: 
H:\BC4\INCLUDE\stdio.h 124: extern  FILE    __cdecl _streams[];
H:\BC4\INCLUDE\stdio.h 125: extern  unsigned    __cdecl _nfile;
H:\BC4\INCLUDE\stdio.h 126: 
H:\BC4\INCLUDE\stdio.h 127: 
H:\BC4\INCLUDE\stdio.h 128: 
H:\BC4\INCLUDE\stdio.h 129: 
H:\BC4\INCLUDE\stdio.h 130: 
H:\BC4\INCLUDE\stdio.h 131: 
H:\BC4\INCLUDE\stdio.h 132: 
H:\BC4\INCLUDE\stdio.h 133: 
H:\BC4\INCLUDE\stdio.h 134: 
H:\BC4\INCLUDE\stdio.h 135: 
H:\BC4\INCLUDE\stdio.h 136: 
H:\BC4\INCLUDE\stdio.h 137: 
H:\BC4\INCLUDE\stdio.h 138: 
H:\BC4\INCLUDE\stdio.h 139: 
H:\BC4\INCLUDE\stdio.h 140: 
H:\BC4\INCLUDE\stdio.h 141: 
H:\BC4\INCLUDE\stdio.h 142: 
H:\BC4\INCLUDE\stdio.h 143: 
H:\BC4\INCLUDE\stdio.h 144: 
H:\BC4\INCLUDE\stdio.h 145: 
H:\BC4\INCLUDE\stdio.h 146: 
H:\BC4\INCLUDE\stdio.h 147: 
H:\BC4\INCLUDE\stdio.h 148: 
H:\BC4\INCLUDE\stdio.h 149: 
H:\BC4\INCLUDE\stdio.h 150: 
H:\BC4\INCLUDE\stdio.h 151: 
H:\BC4\INCLUDE\stdio.h 152: void    __cdecl          clearerr(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 153: int     __cdecl  fclose(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 154: int     __cdecl  fflush(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 155: int     __cdecl  fgetc(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 156: int     __cdecl          fgetpos(FILE  *__stream, fpos_t  *__pos);
H:\BC4\INCLUDE\stdio.h 157: char    *__cdecl  fgets(char  *__s, int __n, FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 158: FILE    *__cdecl  fopen(const char  *__path, const char  *__mode);
H:\BC4\INCLUDE\stdio.h 159: int     __cdecl  fprintf(FILE  *__stream, const char  *__format, ...);
H:\BC4\INCLUDE\stdio.h 160: int     __cdecl  fputc(int __c, FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 161: int     __cdecl  fputs(const char  *__s, FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 162: size_t  __cdecl  fread(void  *__ptr, size_t __size, size_t __n,
H:\BC4\INCLUDE\stdio.h 163: FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 164: FILE    *__cdecl  freopen(const char  *__path, const char  *__mode,
H:\BC4\INCLUDE\stdio.h 165: FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 166: int     __cdecl  fscanf(FILE  *__stream, const char  *__format, ...);
H:\BC4\INCLUDE\stdio.h 167: int     __cdecl  fseek(FILE  *__stream, long __offset, int __whence);
H:\BC4\INCLUDE\stdio.h 168: int     __cdecl          fsetpos(FILE  *__stream, const fpos_t  *__pos);
H:\BC4\INCLUDE\stdio.h 169: long    __cdecl  ftell(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 170: size_t  __cdecl  fwrite(const void  *__ptr, size_t __size, size_t __n,
H:\BC4\INCLUDE\stdio.h 171: FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 172: char    *__cdecl     gets(char  *__s);
H:\BC4\INCLUDE\stdio.h 173: void    __cdecl          perror(const char  *__s);
H:\BC4\INCLUDE\stdio.h 174: int     __cdecl          printf(const char  *__format, ...);
H:\BC4\INCLUDE\stdio.h 175: int     __cdecl          puts(const char  *__s);
H:\BC4\INCLUDE\stdio.h 176: int     __cdecl         remove(const char  *__path);
H:\BC4\INCLUDE\stdio.h 177: int     __cdecl  rename(const char  *__oldname,const char  *__newname);
H:\BC4\INCLUDE\stdio.h 178: void    __cdecl  rewind(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 179: int     __cdecl          scanf(const char  *__format, ...);
H:\BC4\INCLUDE\stdio.h 180: void    __cdecl          setbuf(FILE  *__stream, char  *__buf);
H:\BC4\INCLUDE\stdio.h 181: int     __cdecl  setvbuf(FILE  *__stream, char  *__buf,
H:\BC4\INCLUDE\stdio.h 182: int __type, size_t __size);
H:\BC4\INCLUDE\stdio.h 183: int     __cdecl  sprintf(char  *__buffer, const char  *__format, ...);
H:\BC4\INCLUDE\stdio.h 184: int     __cdecl  sscanf(const char  *__buffer,
H:\BC4\INCLUDE\stdio.h 185: const char  *__format, ...);
H:\BC4\INCLUDE\stdio.h 186: char    *__cdecl  strerror(int __errnum);
H:\BC4\INCLUDE\stdio.h 187: FILE    *__cdecl  tmpfile(void);
H:\BC4\INCLUDE\stdio.h 188: char    *__cdecl  tmpnam(char  *__s);
H:\BC4\INCLUDE\stdio.h 189: int     __cdecl  ungetc(int __c, FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 190: int     __cdecl  vfprintf(FILE  *__stream, const char  *__format,
H:\BC4\INCLUDE\stdio.h 191: void  *__arglist);
H:\BC4\INCLUDE\stdio.h 192: int     __cdecl  vfscanf(FILE  *__stream, const char  *__format,
H:\BC4\INCLUDE\stdio.h 193: void  *__arglist);
H:\BC4\INCLUDE\stdio.h 194: int     __cdecl         vprintf(const char  *__format, void  *__arglist);
H:\BC4\INCLUDE\stdio.h 195: int     __cdecl          vscanf(const char  *__format, void  *__arglist);
H:\BC4\INCLUDE\stdio.h 196: int     __cdecl  vsprintf(char  *__buffer, const char  *__format,
H:\BC4\INCLUDE\stdio.h 197: void  *__arglist);
H:\BC4\INCLUDE\stdio.h 198: int     __cdecl  vsscanf(const char  *__buffer, const char  *__format,
H:\BC4\INCLUDE\stdio.h 199: void  *__arglist);
H:\BC4\INCLUDE\stdio.h 200: int     __cdecl         unlink(const char  *__path);
H:\BC4\INCLUDE\stdio.h 201: int     __cdecl          getc(FILE  *__fp);
H:\BC4\INCLUDE\stdio.h 202: 
H:\BC4\INCLUDE\stdio.h 203: int     __cdecl          getchar(void);
H:\BC4\INCLUDE\stdio.h 204: int     __cdecl          putchar(const int __c);
H:\BC4\INCLUDE\stdio.h 205: 
H:\BC4\INCLUDE\stdio.h 206: int     __cdecl          putc(const int __c, FILE  *__fp);
H:\BC4\INCLUDE\stdio.h 207: int     __cdecl          feof(FILE  *__fp);
H:\BC4\INCLUDE\stdio.h 208: int     __cdecl          ferror(FILE  *__fp);
H:\BC4\INCLUDE\stdio.h 209: 
H:\BC4\INCLUDE\stdio.h 210: int     __cdecl  fcloseall(void);
H:\BC4\INCLUDE\stdio.h 211: FILE     *__cdecl  fdopen(int __handle, char  *__type);
H:\BC4\INCLUDE\stdio.h 212: int     __cdecl  fgetchar(void);
H:\BC4\INCLUDE\stdio.h 213: int     __cdecl  flushall(void);
H:\BC4\INCLUDE\stdio.h 214: int     __cdecl  fputchar(int __c);
H:\BC4\INCLUDE\stdio.h 215: FILE     * __cdecl   _fsopen (const char  *__path, const char  *__mode,
H:\BC4\INCLUDE\stdio.h 216: int __shflag);
H:\BC4\INCLUDE\stdio.h 217: int     __cdecl          getw(FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 218: int     __cdecl          putw(int __w, FILE  *__stream);
H:\BC4\INCLUDE\stdio.h 219: int     __cdecl          rmtmp(void);
H:\BC4\INCLUDE\stdio.h 220: char     * __cdecl  _strerror(const char  *__s);
H:\BC4\INCLUDE\stdio.h 221: char     * __cdecl  tempnam(char  *__dir, char  *__pfx);
H:\BC4\INCLUDE\stdio.h 222: 
H:\BC4\INCLUDE\stdio.h 223: 
H:\BC4\INCLUDE\stdio.h 224: 
H:\BC4\INCLUDE\stdio.h 225: int      __cdecl  _fgetc(FILE  *__stream);           
H:\BC4\INCLUDE\stdio.h 226: int      __cdecl  _fputc(char __c, FILE  *__stream); 
H:\BC4\INCLUDE\stdio.h 227: void     __cdecl _InitEasyWin(void);  
H:\BC4\INCLUDE\stdio.h 228: 
H:\BC4\INCLUDE\stdio.h 229: 
H:\BC4\INCLUDE\stdio.h 230: 
H:\BC4\INCLUDE\stdio.h 231: 
H:\BC4\INCLUDE\stdio.h 232: 
H:\BC4\INCLUDE\stdio.h 233: 
H:\BC4\INCLUDE\stdio.h 234: 
H:\BC4\INCLUDE\stdio.h 235: 
H:\BC4\INCLUDE\stdio.h 236: 
H:\BC4\INCLUDE\stdio.h 237: 
H:\BC4\INCLUDE\stdio.h 238: 
H:\BC4\INCLUDE\stdio.h 239: 
H:\BC4\INCLUDE\stdio.h 240: 
H:\BC4\INCLUDE\stdio.h 241: 
H:\BC4\INCLUDE\stdio.h 242: 
H:\BC4\INCLUDE\stdio.h 243: 
H:\BC4\INCLUDE\stdio.h 244: 
H:\BC4\INCLUDE\stdio.h 245: 
H:\BC4\INCLUDE\stdio.h 246: 
H:\BC4\INCLUDE\stdio.h 247: 
H:\BC4\INCLUDE\stdio.h 248: 
H:\BC4\INCLUDE\stdio.h 249: 
H:\BC4\INCLUDE\stdio.h 250: 
H:\BC4\INCLUDE\stdio.h 251: 
H:\BC4\INCLUDE\stdio.h 252: 
H:\BC4\INCLUDE\stdio.h 253: 
H:\BC4\INCLUDE\stdio.h 254: 
H:\BC4\INCLUDE\stdio.h 255: 
H:\BC4\INCLUDE\stdio.h 256: 
H:\BC4\INCLUDE\stdio.h 257: 
H:\BC4\INCLUDE\stdio.h 258: 
H:\BC4\INCLUDE\stdio.h 259: 
H:\BC4\INCLUDE\stdio.h 260: 
H:\BC4\INCLUDE\stdio.h 261: 
H:\BC4\INCLUDE\stdio.h 262: 
H:\BC4\INCLUDE\stdio.h 263: 
H:\BC4\INCLUDE\stdio.h 264: 
H:\BC4\INCLUDE\stdio.h 265: 
H:\BC4\INCLUDE\stdio.h 266: 
H:\BC4\INCLUDE\stdio.h 267: 
H:\BC4\INCLUDE\stdio.h 268: 
H:\BC4\INCLUDE\stdio.h 269: 
H:\BC4\INCLUDE\stdio.h 270: 
H:\BC4\INCLUDE\stdio.h 271: 
H:\BC4\INCLUDE\stdio.h 272: 
H:\BC4\INCLUDE\stdio.h 273: 
H:\BC4\INCLUDE\stdio.h 274: 
H:\BC4\INCLUDE\stdio.h 275: 
H:\BC4\INCLUDE\stdio.h 276: 
H:\BC4\INCLUDE\stdio.h 277: 
H:\BC4\INCLUDE\stdio.h 278: 
H:\BC4\INCLUDE\stdio.h 279: 
H:\BC4\INCLUDE\stdio.h 280: 
H:\BC4\INCLUDE\stdio.h 281: 
H:\BC4\INCLUDE\stdio.h 282: 
H:\BC4\INCLUDE\stdio.h 283: 
H:\BC4\INCLUDE\stdio.h 284: 
H:\BC4\INCLUDE\stdio.h 285: 
H:\BC4\INCLUDE\stdio.h 286: 
H:\BC4\INCLUDE\stdio.h 287: 
H:\BC4\INCLUDE\stdio.h 288: 
H:\BC4\INCLUDE\stdio.h 289: 
H:\BC4\INCLUDE\stdio.h 290: 
H:\BC4\INCLUDE\stdio.h 291: 
H:\BC4\INCLUDE\stdio.h 292: 
H:\BC4\INCLUDE\stdio.h 293: 
H:\BC4\INCLUDE\stdio.h 294: 
H:\BC4\INCLUDE\stdio.h 295: 
H:\BC4\INCLUDE\stdio.h 296: 
H:\BC4\INCLUDE\stdio.h 297: 
H:\BC4\INCLUDE\stdio.h 298: 
H:\BC4\INCLUDE\stdio.h 299: 
H:\BC4\INCLUDE\stdio.h 300: 
H:\BC4\INCLUDE\stdio.h 301: 
H:\BC4\INCLUDE\stdio.h 302: 
H:\BC4\INCLUDE\stdio.h 303: 
H:\BC4\INCLUDE\stdio.h 304: 
H:\BC4\INCLUDE\stdio.h 305: 
H:\BC4\INCLUDE\stdio.h 306: 
H:\BC4\INCLUDE\stdio.h 307: 
H:\BC4\INCLUDE\stdio.h 308: 
H:\BC4\INCLUDE\stdio.h 309: 
H:\BC4\INCLUDE\stdio.h 310: 
H:\BC4\INCLUDE\stdio.h 311: 
H:\BC4\INCLUDE\stdio.h 312: 
H:\BC4\INCLUDE\stdio.h 313: 
H:\BC4\INCLUDE\stdio.h 314: 
H:\BC4\INCLUDE\stdio.h 315: 
H:\BC4\INCLUDE\stdio.h 316: 
H:\BC4\INCLUDE\stdio.h 317: 
H:\BC4\INCLUDE\stdio.h 318: 
H:\BC4\INCLUDE\stdio.h 319: 
H:\BC4\INCLUDE\stdio.h 320: 
H:\BC4\INCLUDE\stdio.h 321: 
H:\BC4\INCLUDE\stdio.h 322: 
H:\BC4\INCLUDE\stdio.h 323: 
H:\BC4\INCLUDE\stdio.h 324: 
H:\BC4\INCLUDE\stdio.h 325: 
H:\BC4\INCLUDE\stdio.h 326: 
H:\BC4\INCLUDE\stdio.h 327: 
H:\BC4\INCLUDE\stdio.h 328: 
H:\BC4\INCLUDE\stdio.h 329: 
H:\BC4\INCLUDE\stdio.h 330: 
H:\BC4\INCLUDE\stdio.h 331: 
H:\BC4\INCLUDE\stdio.h 332: 
H:\BC4\INCLUDE\stdio.h 333: 
H:\BC4\INCLUDE\stdio.h 334: 
H:\BC4\INCLUDE\stdio.h 335: 
H:\BC4\INCLUDE\stdio.h 336: 
H:\BC4\INCLUDE\stdio.h 337: 
H:\BC4\INCLUDE\stdio.h 338: 
H:\BC4\INCLUDE\stdio.h 339: 
H:\BC4\INCLUDE\stdio.h 340: 
H:\BC4\INCLUDE\stdio.h 341: 
H:\BC4\INCLUDE\stdio.h 342: 
H:\BC4\INCLUDE\stdio.h 343: 
H:\BC4\INCLUDE\stdio.h 344: 
H:\BC4\INCLUDE\stdio.h 345: 
H:\BC4\INCLUDE\stdio.h 346: 
H:\BC4\INCLUDE\stdio.h 347: 
H:\BC4\INCLUDE\stdio.h 348: 
H:\BC4\INCLUDE\stdio.h 349: 
H:\BC4\INCLUDE\stdio.h 350: 
H:\BC4\INCLUDE\stdio.h 351: 
H:\BC4\INCLUDE\stdio.h 352: 
H:\BC4\INCLUDE\stdio.h 353: 
H:\BC4\INCLUDE\stdio.h 354: 
H:\BC4\INCLUDE\stdio.h 355: 
H:\BC4\INCLUDE\stdio.h 356: 
H:\BC4\INCLUDE\stdio.h 357: 
H:\BC4\INCLUDE\stdio.h 358: 
H:\BC4\INCLUDE\stdio.h 359: 
H:\BC4\INCLUDE\stdio.h 360: 
H:\BC4\INCLUDE\stdio.h 361: 
H:\BC4\INCLUDE\stdio.h 362: 
H:\BC4\INCLUDE\stdio.h 363: 
H:\BC4\INCLUDE\stdio.h 364: 
H:\BC4\INCLUDE\stdio.h 365: 
H:\BC4\INCLUDE\stdio.h 366: 
H:\BC4\INCLUDE\stdio.h 367: 
H:\BC4\INCLUDE\stdio.h 368: 
H:\BC4\INCLUDE\stdio.h 369: 
H:\BC4\INCLUDE\stdio.h 370: 
H:\BC4\INCLUDE\stdio.h 371: 
H:\BC4\INCLUDE\stdio.h 372: 
H:\BC4\INCLUDE\stdio.h 373: 
H:\BC4\INCLUDE\stdio.h 374: 
H:\BC4\INCLUDE\stdio.h 375: 
H:\BC4\INCLUDE\stdio.h 376: 
H:\BC4\INCLUDE\stdio.h 377: 
H:\BC4\INCLUDE\stdio.h 378: 
H:\BC4\INCLUDE\stdio.h 379: 
H:\BC4\INCLUDE\stdio.h 380: 
H:\BC4\INCLUDE\stdio.h 381: #pragma option -a. /* restore default packing */
H:\BC4\INCLUDE\stdio.h 382: 
H:\BC4\INCLUDE\stdio.h 383: 
H:\BC4\INCLUDE\stdio.h 384: 
H:\BC4\INCLUDE\stdio.h 385: 
H:\BC4\INCLUDE\stdio.h 386: 
c:\unimel\kalman\kaltest.c 4: 
H:\BC4\INCLUDE\stdlib.h 1: 
H:\BC4\INCLUDE\stdlib.h 2: 
H:\BC4\INCLUDE\stdlib.h 3: 
H:\BC4\INCLUDE\stdlib.h 4: 
H:\BC4\INCLUDE\stdlib.h 5: 
H:\BC4\INCLUDE\stdlib.h 6: 
H:\BC4\INCLUDE\stdlib.h 7: 
H:\BC4\INCLUDE\stdlib.h 8: 
H:\BC4\INCLUDE\stdlib.h 9: 
H:\BC4\INCLUDE\stdlib.h 10: 
H:\BC4\INCLUDE\stdlib.h 11: 
H:\BC4\INCLUDE\stdlib.h 12: 
H:\BC4\INCLUDE\stdlib.h 13: 
H:\BC4\INCLUDE\stdlib.h 14: 
H:\BC4\INCLUDE\stdlib.h 15: 
H:\BC4\INCLUDE\stdlib.h 16: 
H:\BC4\INCLUDE\stdlib.h 17: 
H:\BC4\INCLUDE\stdlib.h 18: 
H:\BC4\INCLUDE\stdlib.h 19: 
H:\BC4\INCLUDE\stdlib.h 20: 
H:\BC4\INCLUDE\stdlib.h 21: 
H:\BC4\INCLUDE\stdlib.h 22: 
H:\BC4\INCLUDE\stdlib.h 23: 
H:\BC4\INCLUDE\stdlib.h 24: 
H:\BC4\INCLUDE\stdlib.h 25: 
H:\BC4\INCLUDE\stdlib.h 26: 
H:\BC4\INCLUDE\stdlib.h 27: #pragma option -a-
H:\BC4\INCLUDE\stdlib.h 28: 
H:\BC4\INCLUDE\stdlib.h 29: 
H:\BC4\INCLUDE\stdlib.h 30: 
H:\BC4\INCLUDE\stdlib.h 31: 
H:\BC4\INCLUDE\stdlib.h 32: 
H:\BC4\INCLUDE\stdlib.h 33: 
H:\BC4\INCLUDE\stdlib.h 34: 
H:\BC4\INCLUDE\stdlib.h 35: 
H:\BC4\INCLUDE\stdlib.h 36: 
H:\BC4\INCLUDE\stdlib.h 37: typedef struct {
H:\BC4\INCLUDE\stdlib.h 38: int     quot;
H:\BC4\INCLUDE\stdlib.h 39: int     rem;
H:\BC4\INCLUDE\stdlib.h 40: } div_t;
H:\BC4\INCLUDE\stdlib.h 41: 
H:\BC4\INCLUDE\stdlib.h 42: 
H:\BC4\INCLUDE\stdlib.h 43: 
H:\BC4\INCLUDE\stdlib.h 44: 
H:\BC4\INCLUDE\stdlib.h 45: typedef struct {
H:\BC4\INCLUDE\stdlib.h 46: long    quot;
H:\BC4\INCLUDE\stdlib.h 47: long    rem;
H:\BC4\INCLUDE\stdlib.h 48: } ldiv_t;
H:\BC4\INCLUDE\stdlib.h 49: 
H:\BC4\INCLUDE\stdlib.h 50: 
H:\BC4\INCLUDE\stdlib.h 51: 
H:\BC4\INCLUDE\stdlib.h 52: 
H:\BC4\INCLUDE\stdlib.h 53: 
H:\BC4\INCLUDE\stdlib.h 54: typedef unsigned short wchar_t;
H:\BC4\INCLUDE\stdlib.h 55: 
H:\BC4\INCLUDE\stdlib.h 56: 
H:\BC4\INCLUDE\stdlib.h 57: 
H:\BC4\INCLUDE\stdlib.h 58: 
H:\BC4\INCLUDE\stdlib.h 59: 
H:\BC4\INCLUDE\stdlib.h 60: 
H:\BC4\INCLUDE\stdlib.h 61: 
H:\BC4\INCLUDE\stdlib.h 62: 
H:\BC4\INCLUDE\stdlib.h 63: 
H:\BC4\INCLUDE\stdlib.h 64: 
H:\BC4\INCLUDE\stdlib.h 65: 
H:\BC4\INCLUDE\stdlib.h 66: 
H:\BC4\INCLUDE\stdlib.h 67: typedef void (__cdecl * atexit_t)(void);
H:\BC4\INCLUDE\stdlib.h 68: 
H:\BC4\INCLUDE\stdlib.h 69: 
H:\BC4\INCLUDE\stdlib.h 70: 
H:\BC4\INCLUDE\stdlib.h 71: 
H:\BC4\INCLUDE\stdlib.h 72: 
H:\BC4\INCLUDE\stdlib.h 73: 
H:\BC4\INCLUDE\stdlib.h 74: 
H:\BC4\INCLUDE\stdlib.h 75: 
H:\BC4\INCLUDE\stdlib.h 76: 
H:\BC4\INCLUDE\stdlib.h 77: 
H:\BC4\INCLUDE\stdlib.h 78: 
H:\BC4\INCLUDE\stdlib.h 79: 
H:\BC4\INCLUDE\stdlib.h 80: 
H:\BC4\INCLUDE\stdlib.h 81: 
H:\BC4\INCLUDE\stdlib.h 82: 
H:\BC4\INCLUDE\stdlib.h 83: void        __cdecl abort(void);
H:\BC4\INCLUDE\stdlib.h 84: 
H:\BC4\INCLUDE\stdlib.h 85: 
H:\BC4\INCLUDE\stdlib.h 86: 
H:\BC4\INCLUDE\stdlib.h 87: 
H:\BC4\INCLUDE\stdlib.h 88: int         __cdecl __abs__(int);
H:\BC4\INCLUDE\stdlib.h 89: 
H:\BC4\INCLUDE\stdlib.h 90: 
H:\BC4\INCLUDE\stdlib.h 91: 
H:\BC4\INCLUDE\stdlib.h 92: int         __cdecl abs(int __x);
H:\BC4\INCLUDE\stdlib.h 93: 
H:\BC4\INCLUDE\stdlib.h 94: 
H:\BC4\INCLUDE\stdlib.h 95: 
H:\BC4\INCLUDE\stdlib.h 96: 
H:\BC4\INCLUDE\stdlib.h 97: 
H:\BC4\INCLUDE\stdlib.h 98: int         __cdecl  atexit(void (__cdecl *__func)(void));
H:\BC4\INCLUDE\stdlib.h 99: double      __cdecl  atof(const char  *__s);
H:\BC4\INCLUDE\stdlib.h 100: int         __cdecl atoi(const char  *__s);
H:\BC4\INCLUDE\stdlib.h 101: long        __cdecl atol(const char  *__s);
H:\BC4\INCLUDE\stdlib.h 102: void  * __cdecl bsearch(const void  *__key, const void  *__base,
H:\BC4\INCLUDE\stdlib.h 103: size_t __nelem, size_t __width,
H:\BC4\INCLUDE\stdlib.h 104: int (__cdecl *fcmp)(const void  *,
H:\BC4\INCLUDE\stdlib.h 105: const void  *));
H:\BC4\INCLUDE\stdlib.h 106: void  * __cdecl  calloc(size_t __nitems, size_t __size);
H:\BC4\INCLUDE\stdlib.h 107: div_t       __cdecl  div(int __numer, int __denom);
H:\BC4\INCLUDE\stdlib.h 108: void        __cdecl  exit(int __status);
H:\BC4\INCLUDE\stdlib.h 109: void        __cdecl  free(void  *__block);
H:\BC4\INCLUDE\stdlib.h 110: char  * __cdecl getenv(const char  *__name);
H:\BC4\INCLUDE\stdlib.h 111: long        __cdecl  labs(long __x);
H:\BC4\INCLUDE\stdlib.h 112: ldiv_t      __cdecl  ldiv(long __numer, long __denom);
H:\BC4\INCLUDE\stdlib.h 113: void  * __cdecl  malloc(size_t __size);
H:\BC4\INCLUDE\stdlib.h 114: int         __cdecl  mblen(const char  *__s, size_t __n);
H:\BC4\INCLUDE\stdlib.h 115: size_t      __cdecl  mbstowcs(wchar_t  *__pwcs, const char  *__s,
H:\BC4\INCLUDE\stdlib.h 116: size_t __n);
H:\BC4\INCLUDE\stdlib.h 117: int         __cdecl  mbtowc(wchar_t  *__pwc, const char  *__s, size_t __n);
H:\BC4\INCLUDE\stdlib.h 118: void        __cdecl  qsort(void  *__base, size_t __nelem, size_t __width,
H:\BC4\INCLUDE\stdlib.h 119: int __cdecl (* __fcmp)(const void  *, const void  *));
H:\BC4\INCLUDE\stdlib.h 120: int         __cdecl  rand(void);
H:\BC4\INCLUDE\stdlib.h 121: void   *__cdecl  realloc(void  *__block, size_t __size);
H:\BC4\INCLUDE\stdlib.h 122: void        __cdecl  srand(unsigned __seed);
H:\BC4\INCLUDE\stdlib.h 123: double      __cdecl  strtod(const char  *__s, char  * *__endptr);
H:\BC4\INCLUDE\stdlib.h 124: long        __cdecl  strtol(const char  *__s, char  * *__endptr,
H:\BC4\INCLUDE\stdlib.h 125: int __radix);
H:\BC4\INCLUDE\stdlib.h 126: long double __cdecl  _strtold(const char  *__s, char  * *__endptr);
H:\BC4\INCLUDE\stdlib.h 127: unsigned long __cdecl  strtoul(const char  *__s, char  * *__endptr,
H:\BC4\INCLUDE\stdlib.h 128: int __radix);
H:\BC4\INCLUDE\stdlib.h 129: int         __cdecl  system(const char  *__command);
H:\BC4\INCLUDE\stdlib.h 130: size_t      __cdecl  wcstombs(char  *__s, const wchar_t  *__pwcs,
H:\BC4\INCLUDE\stdlib.h 131: size_t __n);
H:\BC4\INCLUDE\stdlib.h 132: int         __cdecl  wctomb(char  *__s, wchar_t __wc);
H:\BC4\INCLUDE\stdlib.h 133: 
H:\BC4\INCLUDE\stdlib.h 134: 
H:\BC4\INCLUDE\stdlib.h 135: 
H:\BC4\INCLUDE\stdlib.h 136: 
H:\BC4\INCLUDE\stdlib.h 137: 
H:\BC4\INCLUDE\stdlib.h 138: extern  unsigned        __cdecl _psp;
H:\BC4\INCLUDE\stdlib.h 139: 
H:\BC4\INCLUDE\stdlib.h 140:  
H:\BC4\INCLUDE\stdlib.h 141: 
H:\BC4\INCLUDE\stdlib.h 142: 
H:\BC4\INCLUDE\stdlib.h 143: 
H:\BC4\INCLUDE\stdlib.h 144: extern  char          **__cdecl _environ;
H:\BC4\INCLUDE\stdlib.h 145: extern  int             __cdecl _fmode;
H:\BC4\INCLUDE\stdlib.h 146: extern  unsigned char   __cdecl _osmajor;
H:\BC4\INCLUDE\stdlib.h 147: extern  unsigned char   __cdecl _osminor;
H:\BC4\INCLUDE\stdlib.h 148: extern  unsigned int    __cdecl _version;
H:\BC4\INCLUDE\stdlib.h 149: 
H:\BC4\INCLUDE\stdlib.h 150: 
H:\BC4\INCLUDE\stdlib.h 151: 
H:\BC4\INCLUDE\stdlib.h 152: 
H:\BC4\INCLUDE\stdlib.h 153: 
H:\BC4\INCLUDE\stdlib.h 154: 
H:\BC4\INCLUDE\stdlib.h 155: 
H:\BC4\INCLUDE\stdlib.h 156: 
H:\BC4\INCLUDE\stdlib.h 157: 
H:\BC4\INCLUDE\stdlib.h 158: 
H:\BC4\INCLUDE\stdlib.h 159: 
H:\BC4\INCLUDE\stdlib.h 160: 
H:\BC4\INCLUDE\stdlib.h 161: 
H:\BC4\INCLUDE\stdlib.h 162: 
H:\BC4\INCLUDE\stdlib.h 163: 
H:\BC4\INCLUDE\stdlib.h 164: 
H:\BC4\INCLUDE\stdlib.h 165: 
H:\BC4\INCLUDE\stdlib.h 166: 
H:\BC4\INCLUDE\stdlib.h 167: 
H:\BC4\INCLUDE\stdlib.h 168: 
H:\BC4\INCLUDE\stdlib.h 169: 
H:\BC4\INCLUDE\stdlib.h 170: extern  char       *__cdecl _sys_errlist[];
H:\BC4\INCLUDE\stdlib.h 171: extern  int             __cdecl _sys_nerr;
H:\BC4\INCLUDE\stdlib.h 172: 
H:\BC4\INCLUDE\stdlib.h 173: 
H:\BC4\INCLUDE\stdlib.h 174: 
H:\BC4\INCLUDE\stdlib.h 175: 
H:\BC4\INCLUDE\stdlib.h 176: 
H:\BC4\INCLUDE\stdlib.h 177: 
H:\BC4\INCLUDE\stdlib.h 178: 
H:\BC4\INCLUDE\stdlib.h 179: 
H:\BC4\INCLUDE\stdlib.h 180: 
H:\BC4\INCLUDE\stdlib.h 181: 
H:\BC4\INCLUDE\stdlib.h 182: 
H:\BC4\INCLUDE\stdlib.h 183: 
H:\BC4\INCLUDE\stdlib.h 184: 
H:\BC4\INCLUDE\stdlib.h 185: 
H:\BC4\INCLUDE\stdlib.h 186: 
H:\BC4\INCLUDE\stdlib.h 187: 
H:\BC4\INCLUDE\stdlib.h 188: 
H:\BC4\INCLUDE\stdlib.h 189: 
H:\BC4\INCLUDE\stdlib.h 190: 
H:\BC4\INCLUDE\stdlib.h 191: 
H:\BC4\INCLUDE\stdlib.h 192: 
H:\BC4\INCLUDE\stdlib.h 193: 
H:\BC4\INCLUDE\stdlib.h 194: 
H:\BC4\INCLUDE\stdlib.h 195: long double    __cdecl   _atold(const char  *__s);
H:\BC4\INCLUDE\stdlib.h 196: unsigned char  __cdecl   _crotl(unsigned char __value, int __count);
H:\BC4\INCLUDE\stdlib.h 197: unsigned char  __cdecl   _crotr(unsigned char __value, int __count);
H:\BC4\INCLUDE\stdlib.h 198: char      *__cdecl   ecvt(double __value, int __ndig, int  *__dec,
H:\BC4\INCLUDE\stdlib.h 199: int  *__sign);
H:\BC4\INCLUDE\stdlib.h 200: void           __cdecl   _exit(int __status);
H:\BC4\INCLUDE\stdlib.h 201: char      *__cdecl   fcvt(double __value, int __ndig, int  *__dec,
H:\BC4\INCLUDE\stdlib.h 202: int  *__sign);
H:\BC4\INCLUDE\stdlib.h 203: char      *__cdecl   _fullpath( char  *__buf,
H:\BC4\INCLUDE\stdlib.h 204: const char  *__path,
H:\BC4\INCLUDE\stdlib.h 205: size_t __maxlen );
H:\BC4\INCLUDE\stdlib.h 206: char      *__cdecl   gcvt(double __value, int __ndec, char  *__buf);
H:\BC4\INCLUDE\stdlib.h 207: char      *__cdecl   itoa(int __value, char  *__string, int __radix);
H:\BC4\INCLUDE\stdlib.h 208: void      *__cdecl    lfind(const void  *__key, const void  *__base,
H:\BC4\INCLUDE\stdlib.h 209: size_t  *__num, size_t __width,
H:\BC4\INCLUDE\stdlib.h 210: int __cdecl(* __fcmp)(const void  *,
H:\BC4\INCLUDE\stdlib.h 211: const void  *));
H:\BC4\INCLUDE\stdlib.h 212: unsigned long  __cdecl   _lrotl(unsigned long __val, int __count);
H:\BC4\INCLUDE\stdlib.h 213: unsigned long  __cdecl   _lrotr(unsigned long __val, int __count);
H:\BC4\INCLUDE\stdlib.h 214: 
H:\BC4\INCLUDE\stdlib.h 215: void      *__cdecl    lsearch(const void  *__key, void  *__base,
H:\BC4\INCLUDE\stdlib.h 216: size_t  *__num, size_t __width,
H:\BC4\INCLUDE\stdlib.h 217: int __cdecl(* __fcmp)(const void  *, const void  *));
H:\BC4\INCLUDE\stdlib.h 218: char      *__cdecl   ltoa(long __value, char  *__string, int __radix);
H:\BC4\INCLUDE\stdlib.h 219: void           __cdecl    _makepath( char  *__path,
H:\BC4\INCLUDE\stdlib.h 220: const char  *__drive,
H:\BC4\INCLUDE\stdlib.h 221: const char  *__dir,
H:\BC4\INCLUDE\stdlib.h 222: const char  *__name,
H:\BC4\INCLUDE\stdlib.h 223: const char  *__ext );
H:\BC4\INCLUDE\stdlib.h 224: int            __cdecl    putenv(const char  *__name);
H:\BC4\INCLUDE\stdlib.h 225: 
H:\BC4\INCLUDE\stdlib.h 226: unsigned       __cdecl   _rotl(unsigned __value, int __count);
H:\BC4\INCLUDE\stdlib.h 227: unsigned       __cdecl   _rotr(unsigned __value, int __count);
H:\BC4\INCLUDE\stdlib.h 228: 
H:\BC4\INCLUDE\stdlib.h 229: unsigned       __cdecl   __rotl__(unsigned __value, int __count);     
H:\BC4\INCLUDE\stdlib.h 230: unsigned       __cdecl   __rotr__(unsigned __value, int __count);     
H:\BC4\INCLUDE\stdlib.h 231: 
H:\BC4\INCLUDE\stdlib.h 232: void           __cdecl   _searchenv(const char  *__file,
H:\BC4\INCLUDE\stdlib.h 233: const char  *__varname,
H:\BC4\INCLUDE\stdlib.h 234: char  *__pathname);
H:\BC4\INCLUDE\stdlib.h 235: void           __cdecl   _searchstr(const char  *__file,
H:\BC4\INCLUDE\stdlib.h 236: const char  *__ipath,
H:\BC4\INCLUDE\stdlib.h 237: char  *__pathname);
H:\BC4\INCLUDE\stdlib.h 238: void           __cdecl    _splitpath( const char  *__path,
H:\BC4\INCLUDE\stdlib.h 239: char  *__drive,
H:\BC4\INCLUDE\stdlib.h 240: char  *__dir,
H:\BC4\INCLUDE\stdlib.h 241: char  *__name,
H:\BC4\INCLUDE\stdlib.h 242: char  *__ext );
H:\BC4\INCLUDE\stdlib.h 243: void           __cdecl    swab(char  *__from, char  *__to, int __nbytes);
H:\BC4\INCLUDE\stdlib.h 244: char      *__cdecl   ultoa(unsigned long __value, char  *__string,
H:\BC4\INCLUDE\stdlib.h 245: int __radix);
H:\BC4\INCLUDE\stdlib.h 246: 
H:\BC4\INCLUDE\stdlib.h 247: 
H:\BC4\INCLUDE\stdlib.h 248: 
H:\BC4\INCLUDE\stdlib.h 249: 
H:\BC4\INCLUDE\stdlib.h 250: 
H:\BC4\INCLUDE\stdlib.h 251: 
H:\BC4\INCLUDE\stdlib.h 252: 
H:\BC4\INCLUDE\stdlib.h 253: 
H:\BC4\INCLUDE\stdlib.h 254: 
H:\BC4\INCLUDE\stdlib.h 255: 
H:\BC4\INCLUDE\stdlib.h 256: 
H:\BC4\INCLUDE\stdlib.h 257:   
H:\BC4\INCLUDE\stdlib.h 258: 
H:\BC4\INCLUDE\stdlib.h 259: 
H:\BC4\INCLUDE\stdlib.h 260: 
H:\BC4\INCLUDE\stdlib.h 261: 
H:\BC4\INCLUDE\stdlib.h 262: 
H:\BC4\INCLUDE\stdlib.h 263: 
H:\BC4\INCLUDE\stdlib.h 264: 
H:\BC4\INCLUDE\stdlib.h 265: 
H:\BC4\INCLUDE\stdlib.h 266: 
H:\BC4\INCLUDE\stdlib.h 267: 
H:\BC4\INCLUDE\stdlib.h 268: 
H:\BC4\INCLUDE\stdlib.h 269: 
H:\BC4\INCLUDE\stdlib.h 270: 
H:\BC4\INCLUDE\stdlib.h 271: 
H:\BC4\INCLUDE\stdlib.h 272: 
H:\BC4\INCLUDE\stdlib.h 273: 
H:\BC4\INCLUDE\stdlib.h 274: 
H:\BC4\INCLUDE\stdlib.h 275: 
H:\BC4\INCLUDE\stdlib.h 276: extern  int   __cdecl _doserrno;
H:\BC4\INCLUDE\stdlib.h 277: extern  int   __cdecl errno;
H:\BC4\INCLUDE\stdlib.h 278: 
H:\BC4\INCLUDE\stdlib.h 279: 
H:\BC4\INCLUDE\stdlib.h 280: 
H:\BC4\INCLUDE\stdlib.h 281: 
H:\BC4\INCLUDE\stdlib.h 282: 
H:\BC4\INCLUDE\stdlib.h 283: 
H:\BC4\INCLUDE\stdlib.h 284: 
H:\BC4\INCLUDE\stdlib.h 285: 
H:\BC4\INCLUDE\stdlib.h 286: 
H:\BC4\INCLUDE\stdlib.h 287: 
H:\BC4\INCLUDE\stdlib.h 288: 
H:\BC4\INCLUDE\stdlib.h 289: 
H:\BC4\INCLUDE\stdlib.h 290: 
H:\BC4\INCLUDE\stdlib.h 291: 
H:\BC4\INCLUDE\stdlib.h 292: 
H:\BC4\INCLUDE\stdlib.h 293: 
H:\BC4\INCLUDE\stdlib.h 294: 
H:\BC4\INCLUDE\stdlib.h 295: 
H:\BC4\INCLUDE\stdlib.h 296: 
H:\BC4\INCLUDE\stdlib.h 297: 
H:\BC4\INCLUDE\stdlib.h 298: 
H:\BC4\INCLUDE\stdlib.h 299: 
H:\BC4\INCLUDE\stdlib.h 300: 
H:\BC4\INCLUDE\stdlib.h 301: 
H:\BC4\INCLUDE\stdlib.h 302: 
H:\BC4\INCLUDE\stdlib.h 303: 
H:\BC4\INCLUDE\stdlib.h 304: 
H:\BC4\INCLUDE\stdlib.h 305: 
H:\BC4\INCLUDE\stdlib.h 306: 
H:\BC4\INCLUDE\stdlib.h 307: 
H:\BC4\INCLUDE\stdlib.h 308: 
H:\BC4\INCLUDE\stdlib.h 309: 
H:\BC4\INCLUDE\stdlib.h 310: 
H:\BC4\INCLUDE\stdlib.h 311: 
H:\BC4\INCLUDE\stdlib.h 312: 
H:\BC4\INCLUDE\stdlib.h 313: 
H:\BC4\INCLUDE\stdlib.h 314: 
H:\BC4\INCLUDE\stdlib.h 315: 
H:\BC4\INCLUDE\stdlib.h 316: 
H:\BC4\INCLUDE\stdlib.h 317: 
H:\BC4\INCLUDE\stdlib.h 318: 
H:\BC4\INCLUDE\stdlib.h 319: 
H:\BC4\INCLUDE\stdlib.h 320: 
H:\BC4\INCLUDE\stdlib.h 321: 
H:\BC4\INCLUDE\stdlib.h 322: 
H:\BC4\INCLUDE\stdlib.h 323: 
H:\BC4\INCLUDE\stdlib.h 324: 
H:\BC4\INCLUDE\stdlib.h 325: 
H:\BC4\INCLUDE\stdlib.h 326: 
H:\BC4\INCLUDE\stdlib.h 327: 
H:\BC4\INCLUDE\stdlib.h 328: 
H:\BC4\INCLUDE\stdlib.h 329: 
H:\BC4\INCLUDE\stdlib.h 330: 
H:\BC4\INCLUDE\stdlib.h 331: 
H:\BC4\INCLUDE\stdlib.h 332: 
H:\BC4\INCLUDE\stdlib.h 333: 
H:\BC4\INCLUDE\stdlib.h 334: 
H:\BC4\INCLUDE\stdlib.h 335: 
H:\BC4\INCLUDE\stdlib.h 336: 
H:\BC4\INCLUDE\stdlib.h 337: 
H:\BC4\INCLUDE\stdlib.h 338: 
H:\BC4\INCLUDE\stdlib.h 339: 
H:\BC4\INCLUDE\stdlib.h 340: 
H:\BC4\INCLUDE\stdlib.h 341: 
H:\BC4\INCLUDE\stdlib.h 342: 
H:\BC4\INCLUDE\stdlib.h 343: 
H:\BC4\INCLUDE\stdlib.h 344: 
H:\BC4\INCLUDE\stdlib.h 345: 
H:\BC4\INCLUDE\stdlib.h 346: 
H:\BC4\INCLUDE\stdlib.h 347: 
H:\BC4\INCLUDE\stdlib.h 348: 
H:\BC4\INCLUDE\stdlib.h 349: 
H:\BC4\INCLUDE\stdlib.h 350: 
H:\BC4\INCLUDE\stdlib.h 351: 
H:\BC4\INCLUDE\stdlib.h 352: 
H:\BC4\INCLUDE\stdlib.h 353: 
H:\BC4\INCLUDE\stdlib.h 354: 
H:\BC4\INCLUDE\stdlib.h 355: 
H:\BC4\INCLUDE\stdlib.h 356: 
H:\BC4\INCLUDE\stdlib.h 357: 
H:\BC4\INCLUDE\stdlib.h 358: 
H:\BC4\INCLUDE\stdlib.h 359: 
H:\BC4\INCLUDE\stdlib.h 360: 
H:\BC4\INCLUDE\stdlib.h 361: 
H:\BC4\INCLUDE\stdlib.h 362: 
H:\BC4\INCLUDE\stdlib.h 363: 
H:\BC4\INCLUDE\stdlib.h 364: 
H:\BC4\INCLUDE\stdlib.h 365: 
H:\BC4\INCLUDE\stdlib.h 366: 
H:\BC4\INCLUDE\stdlib.h 367: 
H:\BC4\INCLUDE\stdlib.h 368: 
H:\BC4\INCLUDE\stdlib.h 369: 
H:\BC4\INCLUDE\stdlib.h 370: 
H:\BC4\INCLUDE\stdlib.h 371: 
H:\BC4\INCLUDE\stdlib.h 372: 
H:\BC4\INCLUDE\stdlib.h 373: 
H:\BC4\INCLUDE\stdlib.h 374: 
H:\BC4\INCLUDE\stdlib.h 375: 
H:\BC4\INCLUDE\stdlib.h 376: 
H:\BC4\INCLUDE\stdlib.h 377: 
H:\BC4\INCLUDE\stdlib.h 378: 
H:\BC4\INCLUDE\stdlib.h 379: 
H:\BC4\INCLUDE\stdlib.h 380: 
H:\BC4\INCLUDE\stdlib.h 381: 
H:\BC4\INCLUDE\stdlib.h 382: 
H:\BC4\INCLUDE\stdlib.h 383: 
H:\BC4\INCLUDE\stdlib.h 384: 
H:\BC4\INCLUDE\stdlib.h 385: 
H:\BC4\INCLUDE\stdlib.h 386: 
H:\BC4\INCLUDE\stdlib.h 387: 
H:\BC4\INCLUDE\stdlib.h 388: 
H:\BC4\INCLUDE\stdlib.h 389: 
H:\BC4\INCLUDE\stdlib.h 390: 
H:\BC4\INCLUDE\stdlib.h 391: 
H:\BC4\INCLUDE\stdlib.h 392: 
H:\BC4\INCLUDE\stdlib.h 393: 
H:\BC4\INCLUDE\stdlib.h 394: 
H:\BC4\INCLUDE\stdlib.h 395: 
H:\BC4\INCLUDE\stdlib.h 396: 
H:\BC4\INCLUDE\stdlib.h 397: 
H:\BC4\INCLUDE\stdlib.h 398: 
H:\BC4\INCLUDE\stdlib.h 399: 
H:\BC4\INCLUDE\stdlib.h 400: 
H:\BC4\INCLUDE\stdlib.h 401: 
H:\BC4\INCLUDE\stdlib.h 402: 
H:\BC4\INCLUDE\stdlib.h 403: 
H:\BC4\INCLUDE\stdlib.h 404: 
H:\BC4\INCLUDE\stdlib.h 405: 
H:\BC4\INCLUDE\stdlib.h 406: 
H:\BC4\INCLUDE\stdlib.h 407: 
H:\BC4\INCLUDE\stdlib.h 408: 
H:\BC4\INCLUDE\stdlib.h 409: 
H:\BC4\INCLUDE\stdlib.h 410: 
H:\BC4\INCLUDE\stdlib.h 411: 
H:\BC4\INCLUDE\stdlib.h 412: 
H:\BC4\INCLUDE\stdlib.h 413: 
H:\BC4\INCLUDE\stdlib.h 414: 
H:\BC4\INCLUDE\stdlib.h 415: 
H:\BC4\INCLUDE\stdlib.h 416: 
H:\BC4\INCLUDE\stdlib.h 417: 
H:\BC4\INCLUDE\stdlib.h 418: 
H:\BC4\INCLUDE\stdlib.h 419: 
H:\BC4\INCLUDE\stdlib.h 420: 
H:\BC4\INCLUDE\stdlib.h 421: 
H:\BC4\INCLUDE\stdlib.h 422: 
H:\BC4\INCLUDE\stdlib.h 423: 
H:\BC4\INCLUDE\stdlib.h 424: 
H:\BC4\INCLUDE\stdlib.h 425: 
H:\BC4\INCLUDE\stdlib.h 426: 
H:\BC4\INCLUDE\stdlib.h 427: 
H:\BC4\INCLUDE\stdlib.h 428: 
H:\BC4\INCLUDE\stdlib.h 429: 
H:\BC4\INCLUDE\stdlib.h 430: 
H:\BC4\INCLUDE\stdlib.h 431: 
H:\BC4\INCLUDE\stdlib.h 432: 
H:\BC4\INCLUDE\stdlib.h 433: 
H:\BC4\INCLUDE\stdlib.h 434: 
H:\BC4\INCLUDE\stdlib.h 435: 
H:\BC4\INCLUDE\stdlib.h 436: 
H:\BC4\INCLUDE\stdlib.h 437: 
H:\BC4\INCLUDE\stdlib.h 438: 
H:\BC4\INCLUDE\stdlib.h 439: 
H:\BC4\INCLUDE\stdlib.h 440: 
H:\BC4\INCLUDE\stdlib.h 441: 
H:\BC4\INCLUDE\stdlib.h 442: 
H:\BC4\INCLUDE\stdlib.h 443: 
H:\BC4\INCLUDE\stdlib.h 444: 
H:\BC4\INCLUDE\stdlib.h 445: 
H:\BC4\INCLUDE\stdlib.h 446: 
H:\BC4\INCLUDE\stdlib.h 447: 
H:\BC4\INCLUDE\stdlib.h 448: 
H:\BC4\INCLUDE\stdlib.h 449: 
H:\BC4\INCLUDE\stdlib.h 450: 
H:\BC4\INCLUDE\stdlib.h 451: 
H:\BC4\INCLUDE\stdlib.h 452: 
H:\BC4\INCLUDE\stdlib.h 453: 
H:\BC4\INCLUDE\stdlib.h 454: 
H:\BC4\INCLUDE\stdlib.h 455: 
H:\BC4\INCLUDE\stdlib.h 456: 
H:\BC4\INCLUDE\stdlib.h 457: 
H:\BC4\INCLUDE\stdlib.h 458: 
H:\BC4\INCLUDE\stdlib.h 459: 
H:\BC4\INCLUDE\stdlib.h 460: 
H:\BC4\INCLUDE\stdlib.h 461: 
H:\BC4\INCLUDE\stdlib.h 462: 
H:\BC4\INCLUDE\stdlib.h 463: 
H:\BC4\INCLUDE\stdlib.h 464: 
H:\BC4\INCLUDE\stdlib.h 465: 
H:\BC4\INCLUDE\stdlib.h 466: 
H:\BC4\INCLUDE\stdlib.h 467: 
H:\BC4\INCLUDE\stdlib.h 468: 
H:\BC4\INCLUDE\stdlib.h 469: 
H:\BC4\INCLUDE\stdlib.h 470: 
H:\BC4\INCLUDE\stdlib.h 471: 
H:\BC4\INCLUDE\stdlib.h 472: 
H:\BC4\INCLUDE\stdlib.h 473: 
H:\BC4\INCLUDE\stdlib.h 474: 
H:\BC4\INCLUDE\stdlib.h 475: 
H:\BC4\INCLUDE\stdlib.h 476: 
H:\BC4\INCLUDE\stdlib.h 477: 
H:\BC4\INCLUDE\stdlib.h 478: 
H:\BC4\INCLUDE\stdlib.h 479: 
H:\BC4\INCLUDE\stdlib.h 480: 
H:\BC4\INCLUDE\stdlib.h 481: 
H:\BC4\INCLUDE\stdlib.h 482: 
H:\BC4\INCLUDE\stdlib.h 483: 
H:\BC4\INCLUDE\stdlib.h 484: 
H:\BC4\INCLUDE\stdlib.h 485: 
H:\BC4\INCLUDE\stdlib.h 486: 
H:\BC4\INCLUDE\stdlib.h 487: 
H:\BC4\INCLUDE\stdlib.h 488: 
H:\BC4\INCLUDE\stdlib.h 489: 
H:\BC4\INCLUDE\stdlib.h 490: 
H:\BC4\INCLUDE\stdlib.h 491: 
H:\BC4\INCLUDE\stdlib.h 492: 
H:\BC4\INCLUDE\stdlib.h 493: 
H:\BC4\INCLUDE\stdlib.h 494: 
H:\BC4\INCLUDE\stdlib.h 495: 
H:\BC4\INCLUDE\stdlib.h 496: 
H:\BC4\INCLUDE\stdlib.h 497: 
H:\BC4\INCLUDE\stdlib.h 498: 
H:\BC4\INCLUDE\stdlib.h 499: 
H:\BC4\INCLUDE\stdlib.h 500: 
H:\BC4\INCLUDE\stdlib.h 501: 
H:\BC4\INCLUDE\stdlib.h 502: 
H:\BC4\INCLUDE\stdlib.h 503: 
H:\BC4\INCLUDE\stdlib.h 504: 
H:\BC4\INCLUDE\stdlib.h 505: 
H:\BC4\INCLUDE\stdlib.h 506: 
H:\BC4\INCLUDE\stdlib.h 507: 
H:\BC4\INCLUDE\stdlib.h 508: 
H:\BC4\INCLUDE\stdlib.h 509: 
H:\BC4\INCLUDE\stdlib.h 510: 
H:\BC4\INCLUDE\stdlib.h 511: 
H:\BC4\INCLUDE\stdlib.h 512: 
H:\BC4\INCLUDE\stdlib.h 513: 
H:\BC4\INCLUDE\stdlib.h 514: 
H:\BC4\INCLUDE\stdlib.h 515: 
H:\BC4\INCLUDE\stdlib.h 516: 
H:\BC4\INCLUDE\stdlib.h 517: 
H:\BC4\INCLUDE\stdlib.h 518: 
H:\BC4\INCLUDE\stdlib.h 519: 
H:\BC4\INCLUDE\stdlib.h 520: 
H:\BC4\INCLUDE\stdlib.h 521: 
H:\BC4\INCLUDE\stdlib.h 522: 
H:\BC4\INCLUDE\stdlib.h 523: 
H:\BC4\INCLUDE\stdlib.h 524: 
H:\BC4\INCLUDE\stdlib.h 525: 
H:\BC4\INCLUDE\stdlib.h 526: 
H:\BC4\INCLUDE\stdlib.h 527: 
H:\BC4\INCLUDE\stdlib.h 528: 
H:\BC4\INCLUDE\stdlib.h 529: 
H:\BC4\INCLUDE\stdlib.h 530: 
H:\BC4\INCLUDE\stdlib.h 531: 
H:\BC4\INCLUDE\stdlib.h 532: 
H:\BC4\INCLUDE\stdlib.h 533: 
H:\BC4\INCLUDE\stdlib.h 534: 
H:\BC4\INCLUDE\stdlib.h 535: 
H:\BC4\INCLUDE\stdlib.h 536: 
H:\BC4\INCLUDE\stdlib.h 537: 
H:\BC4\INCLUDE\stdlib.h 538: 
H:\BC4\INCLUDE\stdlib.h 539: 
H:\BC4\INCLUDE\stdlib.h 540: 
H:\BC4\INCLUDE\stdlib.h 541: 
H:\BC4\INCLUDE\stdlib.h 542: 
H:\BC4\INCLUDE\stdlib.h 543: 
H:\BC4\INCLUDE\stdlib.h 544: 
H:\BC4\INCLUDE\stdlib.h 545: 
H:\BC4\INCLUDE\stdlib.h 546: 
H:\BC4\INCLUDE\stdlib.h 547: 
H:\BC4\INCLUDE\stdlib.h 548: 
H:\BC4\INCLUDE\stdlib.h 549: 
H:\BC4\INCLUDE\stdlib.h 550: 
H:\BC4\INCLUDE\stdlib.h 551: 
H:\BC4\INCLUDE\stdlib.h 552: 
H:\BC4\INCLUDE\stdlib.h 553: 
H:\BC4\INCLUDE\stdlib.h 554: 
H:\BC4\INCLUDE\stdlib.h 555: 
H:\BC4\INCLUDE\stdlib.h 556: #pragma option -a.  /* restore default packing */
H:\BC4\INCLUDE\stdlib.h 557: 
H:\BC4\INCLUDE\stdlib.h 558: 
H:\BC4\INCLUDE\stdlib.h 559: 
H:\BC4\INCLUDE\stdlib.h 560: 
H:\BC4\INCLUDE\stdlib.h 561: 
c:\unimel\kalman\kaltest.c 5: 
H:\BC4\INCLUDE\time.h 1: 
H:\BC4\INCLUDE\time.h 2: 
H:\BC4\INCLUDE\time.h 3: 
H:\BC4\INCLUDE\time.h 4: 
H:\BC4\INCLUDE\time.h 5: 
H:\BC4\INCLUDE\time.h 6: 
H:\BC4\INCLUDE\time.h 7: 
H:\BC4\INCLUDE\time.h 8: 
H:\BC4\INCLUDE\time.h 9: 
H:\BC4\INCLUDE\time.h 10: 
H:\BC4\INCLUDE\time.h 11: 
H:\BC4\INCLUDE\time.h 12: 
H:\BC4\INCLUDE\time.h 13: 
H:\BC4\INCLUDE\time.h 14: 
H:\BC4\INCLUDE\time.h 15: 
H:\BC4\INCLUDE\time.h 16: 
H:\BC4\INCLUDE\time.h 17: 
H:\BC4\INCLUDE\time.h 18: 
H:\BC4\INCLUDE\time.h 19: 
H:\BC4\INCLUDE\time.h 20: 
H:\BC4\INCLUDE\time.h 21: 
H:\BC4\INCLUDE\time.h 22: 
H:\BC4\INCLUDE\time.h 23: #pragma option -a-
H:\BC4\INCLUDE\time.h 24: 
H:\BC4\INCLUDE\time.h 25: 
H:\BC4\INCLUDE\time.h 26: 
H:\BC4\INCLUDE\time.h 27: 
H:\BC4\INCLUDE\time.h 28: 
H:\BC4\INCLUDE\time.h 29: 
H:\BC4\INCLUDE\time.h 30: 
H:\BC4\INCLUDE\time.h 31: 
H:\BC4\INCLUDE\time.h 32: 
H:\BC4\INCLUDE\time.h 33: typedef long time_t;
H:\BC4\INCLUDE\time.h 34: 
H:\BC4\INCLUDE\time.h 35: 
H:\BC4\INCLUDE\time.h 36: 
H:\BC4\INCLUDE\time.h 37: 
H:\BC4\INCLUDE\time.h 38: typedef long clock_t;
H:\BC4\INCLUDE\time.h 39: 
H:\BC4\INCLUDE\time.h 40: 
H:\BC4\INCLUDE\time.h 41: 
H:\BC4\INCLUDE\time.h 42: 
H:\BC4\INCLUDE\time.h 43: 
H:\BC4\INCLUDE\time.h 44: struct tm
H:\BC4\INCLUDE\time.h 45: {
H:\BC4\INCLUDE\time.h 46: int   tm_sec;
H:\BC4\INCLUDE\time.h 47: int   tm_min;
H:\BC4\INCLUDE\time.h 48: int   tm_hour;
H:\BC4\INCLUDE\time.h 49: int   tm_mday;
H:\BC4\INCLUDE\time.h 50: int   tm_mon;
H:\BC4\INCLUDE\time.h 51: int   tm_year;
H:\BC4\INCLUDE\time.h 52: int   tm_wday;
H:\BC4\INCLUDE\time.h 53: int   tm_yday;
H:\BC4\INCLUDE\time.h 54: int   tm_isdst;
H:\BC4\INCLUDE\time.h 55: };
H:\BC4\INCLUDE\time.h 56: 
H:\BC4\INCLUDE\time.h 57: 
H:\BC4\INCLUDE\time.h 58: 
H:\BC4\INCLUDE\time.h 59: 
H:\BC4\INCLUDE\time.h 60: char  * __cdecl    asctime(const struct tm  *__tblock);
H:\BC4\INCLUDE\time.h 61: char  * __cdecl    ctime(const time_t  *__time);
H:\BC4\INCLUDE\time.h 62: double      __cdecl  difftime(time_t __time2, time_t __time1);
H:\BC4\INCLUDE\time.h 63: struct tm  * __cdecl  gmtime(const time_t  *__timer);
H:\BC4\INCLUDE\time.h 64: struct tm  * __cdecl  localtime(const time_t  *__timer);
H:\BC4\INCLUDE\time.h 65: time_t      __cdecl  time(time_t  *__timer);
H:\BC4\INCLUDE\time.h 66: time_t      __cdecl    mktime(struct tm  *__timeptr);
H:\BC4\INCLUDE\time.h 67: clock_t     __cdecl  clock(void);
H:\BC4\INCLUDE\time.h 68: size_t      __cdecl    strftime(char  *__s, size_t __maxsize,
H:\BC4\INCLUDE\time.h 69: const char  *__fmt, const struct tm  *__t);
H:\BC4\INCLUDE\time.h 70: size_t      __cdecl    _lstrftime(char  *__s, size_t __maxsize,
H:\BC4\INCLUDE\time.h 71: const char  *__fmt, const struct tm  *__t);
H:\BC4\INCLUDE\time.h 72: 
H:\BC4\INCLUDE\time.h 73:   
H:\BC4\INCLUDE\time.h 74: 
H:\BC4\INCLUDE\time.h 75: 
H:\BC4\INCLUDE\time.h 76: 
H:\BC4\INCLUDE\time.h 77: 
H:\BC4\INCLUDE\time.h 78: 
H:\BC4\INCLUDE\time.h 79:   
H:\BC4\INCLUDE\time.h 80: 
H:\BC4\INCLUDE\time.h 81: extern int               __cdecl  _daylight;
H:\BC4\INCLUDE\time.h 82: extern long              __cdecl  _timezone;
H:\BC4\INCLUDE\time.h 83: extern char  * const __cdecl  _tzname[2];
H:\BC4\INCLUDE\time.h 84: 
H:\BC4\INCLUDE\time.h 85: 
H:\BC4\INCLUDE\time.h 86: 
H:\BC4\INCLUDE\time.h 87: 
H:\BC4\INCLUDE\time.h 88: 
H:\BC4\INCLUDE\time.h 89: 
H:\BC4\INCLUDE\time.h 90: 
H:\BC4\INCLUDE\time.h 91: 
H:\BC4\INCLUDE\time.h 92: 
H:\BC4\INCLUDE\time.h 93: 
H:\BC4\INCLUDE\time.h 94: 
H:\BC4\INCLUDE\time.h 95: 
H:\BC4\INCLUDE\time.h 96: 
H:\BC4\INCLUDE\time.h 97: int         __cdecl           stime(time_t  *__tp);
H:\BC4\INCLUDE\time.h 98: void        __cdecl   tzset(void);
H:\BC4\INCLUDE\time.h 99: char  * __cdecl   _strdate(char  *datestr);
H:\BC4\INCLUDE\time.h 100: char  * __cdecl   _strtime(char  *timestr);
H:\BC4\INCLUDE\time.h 101: 
H:\BC4\INCLUDE\time.h 102: 
H:\BC4\INCLUDE\time.h 103: 
H:\BC4\INCLUDE\time.h 104: 
H:\BC4\INCLUDE\time.h 105: 
H:\BC4\INCLUDE\time.h 106: 
H:\BC4\INCLUDE\time.h 107: 
H:\BC4\INCLUDE\time.h 108: 
H:\BC4\INCLUDE\time.h 109: 
H:\BC4\INCLUDE\time.h 110: 
H:\BC4\INCLUDE\time.h 111: 
H:\BC4\INCLUDE\time.h 112: 
H:\BC4\INCLUDE\time.h 113: 
H:\BC4\INCLUDE\time.h 114: 
H:\BC4\INCLUDE\time.h 115: 
H:\BC4\INCLUDE\time.h 116: 
H:\BC4\INCLUDE\time.h 117: 
H:\BC4\INCLUDE\time.h 118: #pragma option -a. /* restore default packing */
H:\BC4\INCLUDE\time.h 119: 
H:\BC4\INCLUDE\time.h 120: 
H:\BC4\INCLUDE\time.h 121: 
H:\BC4\INCLUDE\time.h 122: 
H:\BC4\INCLUDE\time.h 123: 
c:\unimel\kalman\kaltest.c 6: 
kalman.h 1: 
H:\BC4\INCLUDE\time.h 1: 
H:\BC4\INCLUDE\time.h 2: 
H:\BC4\INCLUDE\time.h 3: 
H:\BC4\INCLUDE\time.h 4: 
H:\BC4\INCLUDE\time.h 5: 
H:\BC4\INCLUDE\time.h 6: 
H:\BC4\INCLUDE\time.h 7: 
H:\BC4\INCLUDE\time.h 8: 
H:\BC4\INCLUDE\time.h 9: 
H:\BC4\INCLUDE\time.h 10: 
H:\BC4\INCLUDE\time.h 11: 
H:\BC4\INCLUDE\time.h 12: 
H:\BC4\INCLUDE\time.h 13: 
H:\BC4\INCLUDE\time.h 14: 
H:\BC4\INCLUDE\time.h 15: 
H:\BC4\INCLUDE\time.h 16: 
H:\BC4\INCLUDE\time.h 17: 
H:\BC4\INCLUDE\time.h 18: 
H:\BC4\INCLUDE\time.h 19: 
H:\BC4\INCLUDE\time.h 20: 
H:\BC4\INCLUDE\time.h 21: 
H:\BC4\INCLUDE\time.h 22: 
H:\BC4\INCLUDE\time.h 23: 
H:\BC4\INCLUDE\time.h 24: 
H:\BC4\INCLUDE\time.h 25: 
H:\BC4\INCLUDE\time.h 26: 
H:\BC4\INCLUDE\time.h 27: 
H:\BC4\INCLUDE\time.h 28: 
H:\BC4\INCLUDE\time.h 29: 
H:\BC4\INCLUDE\time.h 30: 
H:\BC4\INCLUDE\time.h 31: 
H:\BC4\INCLUDE\time.h 32: 
H:\BC4\INCLUDE\time.h 33: 
H:\BC4\INCLUDE\time.h 34: 
H:\BC4\INCLUDE\time.h 35: 
H:\BC4\INCLUDE\time.h 36: 
H:\BC4\INCLUDE\time.h 37: 
H:\BC4\INCLUDE\time.h 38: 
H:\BC4\INCLUDE\time.h 39: 
H:\BC4\INCLUDE\time.h 40: 
H:\BC4\INCLUDE\time.h 41: 
H:\BC4\INCLUDE\time.h 42: 
H:\BC4\INCLUDE\time.h 43: 
H:\BC4\INCLUDE\time.h 44: 
H:\BC4\INCLUDE\time.h 45: 
H:\BC4\INCLUDE\time.h 46: 
H:\BC4\INCLUDE\time.h 47: 
H:\BC4\INCLUDE\time.h 48: 
H:\BC4\INCLUDE\time.h 49: 
H:\BC4\INCLUDE\time.h 50: 
H:\BC4\INCLUDE\time.h 51: 
H:\BC4\INCLUDE\time.h 52: 
H:\BC4\INCLUDE\time.h 53: 
H:\BC4\INCLUDE\time.h 54: 
H:\BC4\INCLUDE\time.h 55: 
H:\BC4\INCLUDE\time.h 56: 
H:\BC4\INCLUDE\time.h 57: 
H:\BC4\INCLUDE\time.h 58: 
H:\BC4\INCLUDE\time.h 59: 
H:\BC4\INCLUDE\time.h 60: 
H:\BC4\INCLUDE\time.h 61: 
H:\BC4\INCLUDE\time.h 62: 
H:\BC4\INCLUDE\time.h 63: 
H:\BC4\INCLUDE\time.h 64: 
H:\BC4\INCLUDE\time.h 65: 
H:\BC4\INCLUDE\time.h 66: 
H:\BC4\INCLUDE\time.h 67: 
H:\BC4\INCLUDE\time.h 68: 
H:\BC4\INCLUDE\time.h 69: 
H:\BC4\INCLUDE\time.h 70: 
H:\BC4\INCLUDE\time.h 71: 
H:\BC4\INCLUDE\time.h 72: 
H:\BC4\INCLUDE\time.h 73: 
H:\BC4\INCLUDE\time.h 74: 
H:\BC4\INCLUDE\time.h 75: 
H:\BC4\INCLUDE\time.h 76: 
H:\BC4\INCLUDE\time.h 77: 
H:\BC4\INCLUDE\time.h 78: 
H:\BC4\INCLUDE\time.h 79: 
H:\BC4\INCLUDE\time.h 80: 
H:\BC4\INCLUDE\time.h 81: 
H:\BC4\INCLUDE\time.h 82: 
H:\BC4\INCLUDE\time.h 83: 
H:\BC4\INCLUDE\time.h 84: 
H:\BC4\INCLUDE\time.h 85: 
H:\BC4\INCLUDE\time.h 86: 
H:\BC4\INCLUDE\time.h 87: 
H:\BC4\INCLUDE\time.h 88: 
H:\BC4\INCLUDE\time.h 89: 
H:\BC4\INCLUDE\time.h 90: 
H:\BC4\INCLUDE\time.h 91: 
H:\BC4\INCLUDE\time.h 92: 
H:\BC4\INCLUDE\time.h 93: 
H:\BC4\INCLUDE\time.h 94: 
H:\BC4\INCLUDE\time.h 95: 
H:\BC4\INCLUDE\time.h 96: 
H:\BC4\INCLUDE\time.h 97: 
H:\BC4\INCLUDE\time.h 98: 
H:\BC4\INCLUDE\time.h 99: 
H:\BC4\INCLUDE\time.h 100: 
H:\BC4\INCLUDE\time.h 101: 
H:\BC4\INCLUDE\time.h 102: 
H:\BC4\INCLUDE\time.h 103: 
H:\BC4\INCLUDE\time.h 104: 
H:\BC4\INCLUDE\time.h 105: 
H:\BC4\INCLUDE\time.h 106: 
H:\BC4\INCLUDE\time.h 107: 
H:\BC4\INCLUDE\time.h 108: 
H:\BC4\INCLUDE\time.h 109: 
H:\BC4\INCLUDE\time.h 110: 
H:\BC4\INCLUDE\time.h 111: 
H:\BC4\INCLUDE\time.h 112: 
H:\BC4\INCLUDE\time.h 113: 
H:\BC4\INCLUDE\time.h 114: 
H:\BC4\INCLUDE\time.h 115: 
H:\BC4\INCLUDE\time.h 116: 
H:\BC4\INCLUDE\time.h 117: 
H:\BC4\INCLUDE\time.h 118: 
H:\BC4\INCLUDE\time.h 119: 
H:\BC4\INCLUDE\time.h 120: 
H:\BC4\INCLUDE\time.h 121: 
H:\BC4\INCLUDE\time.h 122: 
H:\BC4\INCLUDE\time.h 123: 
kalman.h 2: 
kalman.h 3: double width = 0.7;
kalman.h 4: 
kalman.h 5: extern void hillclimbing_sm(unsigned int *atcustate,double *azcmd,double *elcmd ,
kalman.h 6: double *azmsd, double *elmsd,double *power,
kalman.h 7: unsigned int *kalmanstate,int *flag);
kalman.h 8: 
kalman.h 9: extern double power_calc(double act_az,double act_el,double az,double el,
kalman.h 10: double width);
kalman.h 11: 
kalman.h 12: extern double el_pos_sat(clock_t t);
kalman.h 13: 
kalman.h 14: extern double az_pos_sat(clock_t t);
kalman.h 15: 
kalman.h 16: extern void calc_model(clock_t t,double *a1dimMatrixC);
kalman.h 17: 
kalman.h 18: 
kalman.h 19: 
kalman.h 20: extern void a2a1dimMatprod(double *a2dimMatrixA,double *a1dimMatrixB,
kalman.h 21: double *a1dimMatrixC);
kalman.h 22: 
kalman.h 23: extern void a1a2dimMatprod(double *a1dimMatrixA,double *a2dimMatrixB,
kalman.h 24: double *a1dimMatrixC);
kalman.h 25: 
kalman.h 26: extern void colrowMatprod(double *col,double *row,
kalman.h 27: double *a2dimMatrixC);
kalman.h 28: 
kalman.h 29: extern void rowcolMatprod(double *row,double *col,
kalman.h 30: double *number);
kalman.h 31: 
kalman.h 32: extern void colcolMatsum(double *colA,double *colB,
kalman.h 33: double *colC);
kalman.h 34: 
kalman.h 35: extern void scalcolMatprod(double *scal,double *colB,
kalman.h 36: double *colC);
kalman.h 37: 
kalman.h 38: extern void a2a2dimMatsum(double *a2dimMatrixA,double *a2dimMatrixB,
kalman.h 39: double *a2dimMatrixC);
kalman.h 40: 
kalman.h 41: void IdMatrix(double *a2dimMatrixC);
kalman.h 42: 
kalman.h 43: void a2IdMatprod (double *a2dimMatrixA, double *a2dimMatrixC);
kalman.h 44: 
kalman.h 45: 
kalman.h 46: 
c:\unimel\kalman\kaltest.c 7: 
c:\unimel\kalman\kaltest.c 8: 
c:\unimel\kalman\kaltest.c 9: 
c:\unimel\kalman\kaltest.c 10: 
c:\unimel\kalman\kaltest.c 11: 
c:\unimel\kalman\kaltest.c 12: 
c:\unimel\kalman\kaltest.c 13: 
c:\unimel\kalman\kaltest.c 14: 
c:\unimel\kalman\kaltest.c 15: 
c:\unimel\kalman\kaltest.c 16: 
c:\unimel\kalman\kaltest.c 17: 
c:\unimel\kalman\kaltest.c 18: 
c:\unimel\kalman\kaltest.c 19: 
c:\unimel\kalman\kaltest.c 20: 
c:\unimel\kalman\kaltest.c 21: 
c:\unimel\kalman\kaltest.c 22: 
c:\unimel\kalman\kaltest.c 23: 
c:\unimel\kalman\kaltest.c 24: 
c:\unimel\kalman\kaltest.c 25: 
c:\unimel\kalman\kaltest.c 26: 
c:\unimel\kalman\kaltest.c 27: 
c:\unimel\kalman\kaltest.c 28: static void kalman_sm(unsigned int *atcustate,double *azcmd,double *elcmd,
c:\unimel\kalman\kaltest.c 29: double *azmsd,double *elmsd,double *power,
c:\unimel\kalman\kaltest.c 30: unsigned int atcumode);
c:\unimel\kalman\kaltest.c 31: 
c:\unimel\kalman\kaltest.c 32: unsigned int atcumode,atcustate,kalman_state,update_step;
c:\unimel\kalman\kaltest.c 33: double act_az,act_el,azcmd,elcmd,azmsd,elmsd,power;
c:\unimel\kalman\kaltest.c 34: 
c:\unimel\kalman\kaltest.c 35: clock_t timer;
c:\unimel\kalman\kaltest.c 36: 
c:\unimel\kalman\kaltest.c 37: 
c:\unimel\kalman\kaltest.c 38: static void kalman_sm(unsigned int *atcustate,double *azcmd,double *elcmd,
c:\unimel\kalman\kaltest.c 39: double *azmsd,double *elmsd,double *power,
c:\unimel\kalman\kaltest.c 40: unsigned int atcumode) {
c:\unimel\kalman\kaltest.c 41: 
c:\unimel\kalman\kaltest.c 42: static	double x_az[6],x_el[6],P_cov_az[36],P_cov_el[36],Q_noise[36],
c:\unimel\kalman\kaltest.c 43: R_az[1],R_el[1],K_az[6],K_el[6];
c:\unimel\kalman\kaltest.c 44: static double temp_az1dim[6],temp_az2dim[36],temp_el1dim[6],temp_el2dim[36],
c:\unimel\kalman\kaltest.c 45: temp2_az2dim[36],temp2_el2dim[36],temp_az[1],temp_el[1],minus[1];
c:\unimel\kalman\kaltest.c 46: static	double model;
c:\unimel\kalman\kaltest.c 47: int counter,flag;
c:\unimel\kalman\kaltest.c 48: clock_t t,start_time;
c:\unimel\kalman\kaltest.c 49: 
c:\unimel\kalman\kaltest.c 50: switch(kalman_state) {
c:\unimel\kalman\kaltest.c 51: 
c:\unimel\kalman\kaltest.c 52: case 0 :
c:\unimel\kalman\kaltest.c 53: hillclimbing_sm(atcustate,azcmd,elcmd,azmsd,elmsd,power,
c:\unimel\kalman\kaltest.c 54: &kalman_state,&flag);
c:\unimel\kalman\kaltest.c 55: break;
c:\unimel\kalman\kaltest.c 56: 
c:\unimel\kalman\kaltest.c 57: case 1 :
c:\unimel\kalman\kaltest.c 58: 
c:\unimel\kalman\kaltest.c 59: x_az[0] = *azmsd;
c:\unimel\kalman\kaltest.c 60: x_az[1] = 0;
c:\unimel\kalman\kaltest.c 61: x_az[2] = 0;
c:\unimel\kalman\kaltest.c 62: x_az[3] = 0;
c:\unimel\kalman\kaltest.c 63: x_az[4] = 0;
c:\unimel\kalman\kaltest.c 64: x_az[5] = 0;
c:\unimel\kalman\kaltest.c 65: 
c:\unimel\kalman\kaltest.c 66: x_el[0] = *elmsd;
c:\unimel\kalman\kaltest.c 67: x_el[1] = 0;
c:\unimel\kalman\kaltest.c 68: x_el[2] = 0;
c:\unimel\kalman\kaltest.c 69: x_el[3] = 0;
c:\unimel\kalman\kaltest.c 70: x_el[4] = 0;
c:\unimel\kalman\kaltest.c 71: x_el[5] = 0;
c:\unimel\kalman\kaltest.c 72: 
c:\unimel\kalman\kaltest.c 73: IdMatrix(&P_cov_az);
c:\unimel\kalman\kaltest.c 74: 
c:\unimel\kalman\kaltest.c 75: IdMatrix(&P_cov_el);
c:\unimel\kalman\kaltest.c 76: R_az[0] = 0.2;
c:\unimel\kalman\kaltest.c 77: R_el[0] = 0.2;
c:\unimel\kalman\kaltest.c 78: kalman_state = 2;
c:\unimel\kalman\kaltest.c 79: break;
c:\unimel\kalman\kaltest.c 80: 
c:\unimel\kalman\kaltest.c 81: case 2 :
c:\unimel\kalman\kaltest.c 82: 
c:\unimel\kalman\kaltest.c 83: switch(update_step) {
c:\unimel\kalman\kaltest.c 84: 
c:\unimel\kalman\kaltest.c 85: case 0 :
c:\unimel\kalman\kaltest.c 86: t = clock()/1000.0;
c:\unimel\kalman\kaltest.c 87: calc_model(t,&model);
c:\unimel\kalman\kaltest.c 88: a2a2dimMatsum(&P_cov_az,&Q_noise,&P_cov_az);
c:\unimel\kalman\kaltest.c 89: a2a2dimMatsum(&P_cov_el,&Q_noise,&P_cov_el);
c:\unimel\kalman\kaltest.c 90: update_step = 1;
c:\unimel\kalman\kaltest.c 91: break;
c:\unimel\kalman\kaltest.c 92: 
c:\unimel\kalman\kaltest.c 93: case 1 :
c:\unimel\kalman\kaltest.c 94: 
c:\unimel\kalman\kaltest.c 95: {	a2a1dimMatprod(&P_cov_az,&model,&temp_az1dim);
c:\unimel\kalman\kaltest.c 96: rowcolMatprod(&model,&temp_az1dim,&temp_az);
c:\unimel\kalman\kaltest.c 97: temp_az[0] = 1/(temp_az[0] + R_az[0]);
c:\unimel\kalman\kaltest.c 98: scalcolMatprod(&temp_az,&model,&temp_az1dim);
c:\unimel\kalman\kaltest.c 99: a2a1dimMatprod(&P_cov_az,&temp_az1dim,&K_az);
c:\unimel\kalman\kaltest.c 100: }
c:\unimel\kalman\kaltest.c 101: update_step = 2;
c:\unimel\kalman\kaltest.c 102: break;
c:\unimel\kalman\kaltest.c 103: 
c:\unimel\kalman\kaltest.c 104: case 2 :
c:\unimel\kalman\kaltest.c 105: 
c:\unimel\kalman\kaltest.c 106: {	a2a1dimMatprod(&P_cov_el,&model,&temp_el1dim);
c:\unimel\kalman\kaltest.c 107: rowcolMatprod(&model,&temp_el1dim,&temp_el);
c:\unimel\kalman\kaltest.c 108: temp_el[0] = 1/(temp_el[0] + R_el[0]);
c:\unimel\kalman\kaltest.c 109: scalcolMatprod(&temp_el,&model,&temp_el1dim);
c:\unimel\kalman\kaltest.c 110: a2a1dimMatprod(&P_cov_el,&temp_el1dim,&K_el);
c:\unimel\kalman\kaltest.c 111: }
c:\unimel\kalman\kaltest.c 112: update_step = 3;
c:\unimel\kalman\kaltest.c 113: break;
c:\unimel\kalman\kaltest.c 114: 
c:\unimel\kalman\kaltest.c 115: case 3 :
c:\unimel\kalman\kaltest.c 116: 
c:\unimel\kalman\kaltest.c 117: {  
c:\unimel\kalman\kaltest.c 118: rowcolMatprod(&model,&x_az,&temp_az);
c:\unimel\kalman\kaltest.c 119: temp_az[0] = *azmsd - temp_az[0];
c:\unimel\kalman\kaltest.c 120: scalcolMatprod(&temp_az,&K_az,&temp_az1dim);
c:\unimel\kalman\kaltest.c 121: colcolMatsum(&x_az,&temp_az1dim,&x_az);
c:\unimel\kalman\kaltest.c 122: 
c:\unimel\kalman\kaltest.c 123: rowcolMatprod(&model,&x_el,&temp_el);
c:\unimel\kalman\kaltest.c 124: temp_el[0] = *elmsd - temp_el[0];
c:\unimel\kalman\kaltest.c 125: scalcolMatprod(&temp_el,&K_el,&temp_el1dim);
c:\unimel\kalman\kaltest.c 126: colcolMatsum(&x_el,&temp_el1dim,&x_el);
c:\unimel\kalman\kaltest.c 127: }
c:\unimel\kalman\kaltest.c 128: update_step = 4;
c:\unimel\kalman\kaltest.c 129: break;
c:\unimel\kalman\kaltest.c 130: 
c:\unimel\kalman\kaltest.c 131: case  4 :
c:\unimel\kalman\kaltest.c 132: 
c:\unimel\kalman\kaltest.c 133: {	minus[0] = -1;
c:\unimel\kalman\kaltest.c 134: 
c:\unimel\kalman\kaltest.c 135: scalcolMatprod(&minus,&K_az,&temp_az1dim);
c:\unimel\kalman\kaltest.c 136: a1a2dimMatprod(&model,&P_cov_az,&temp_az2dim);
c:\unimel\kalman\kaltest.c 137: a1a2dimMatprod(&temp_az1dim,&temp_az2dim,&temp2_az2dim);
c:\unimel\kalman\kaltest.c 138: a2IdMatprod(&P_cov_az,&temp_az2dim);
c:\unimel\kalman\kaltest.c 139: a2a2dimMatsum(&temp_az2dim,&temp2_az2dim,&P_cov_az);
c:\unimel\kalman\kaltest.c 140: 
c:\unimel\kalman\kaltest.c 141: scalcolMatprod(&minus,&K_el,&temp_el1dim);
c:\unimel\kalman\kaltest.c 142: a1a2dimMatprod(&model,&P_cov_el,&temp_el2dim);
c:\unimel\kalman\kaltest.c 143: a1a2dimMatprod(&temp_el1dim,&temp_el2dim,&temp2_el2dim);
c:\unimel\kalman\kaltest.c 144: a2IdMatprod(&P_cov_el,&temp_el2dim);
c:\unimel\kalman\kaltest.c 145: a2a2dimMatsum(&temp_el2dim,&temp2_el2dim,&P_cov_el);
c:\unimel\kalman\kaltest.c 146: }
c:\unimel\kalman\kaltest.c 147: update_step = 0;
c:\unimel\kalman\kaltest.c 148: kalman_state = 3;
c:\unimel\kalman\kaltest.c 149: break;
c:\unimel\kalman\kaltest.c 150: 
c:\unimel\kalman\kaltest.c 151: default : update_step = 0;
c:\unimel\kalman\kaltest.c 152: break;
c:\unimel\kalman\kaltest.c 153: }
c:\unimel\kalman\kaltest.c 154: 
c:\unimel\kalman\kaltest.c 155: case 3 :
c:\unimel\kalman\kaltest.c 156: 
c:\unimel\kalman\kaltest.c 157: {  t = clock()/1000.0,
c:\unimel\kalman\kaltest.c 158: calc_model(t,&model);
c:\unimel\kalman\kaltest.c 159: rowcolMatprod(&model,&x_az,&temp_az);
c:\unimel\kalman\kaltest.c 160: *azcmd = temp_az[0] - '0';
c:\unimel\kalman\kaltest.c 161: rowcolMatprod(&model,&x_el,&temp_el);
c:\unimel\kalman\kaltest.c 162: *elcmd = temp_el[0] - '0';
c:\unimel\kalman\kaltest.c 163: }
c:\unimel\kalman\kaltest.c 164: counter = 25 ;
c:\unimel\kalman\kaltest.c 165: kalman_state = 4;
c:\unimel\kalman\kaltest.c 166: break;
c:\unimel\kalman\kaltest.c 167: 
c:\unimel\kalman\kaltest.c 168: case 4 :
c:\unimel\kalman\kaltest.c 169: if (counter--<0){
c:\unimel\kalman\kaltest.c 170: atcustate = 0;
c:\unimel\kalman\kaltest.c 171: kalman_state = 5;
c:\unimel\kalman\kaltest.c 172: }
c:\unimel\kalman\kaltest.c 173: 
c:\unimel\kalman\kaltest.c 174: case 5 :
c:\unimel\kalman\kaltest.c 175: t = clock()/1000.0;
c:\unimel\kalman\kaltest.c 176: printf("                                   NEXT SHOW AT 100'': ");
c:\unimel\kalman\kaltest.c 177: printf("%d\n",t-start_time);
c:\unimel\kalman\kaltest.c 178: printf("\n");
c:\unimel\kalman\kaltest.c 179: if(t-start_time >= 100) {
c:\unimel\kalman\kaltest.c 180: flag = 1;
c:\unimel\kalman\kaltest.c 181: kalman_state = 0;
c:\unimel\kalman\kaltest.c 182: start_time = clock()/1000.0;
c:\unimel\kalman\kaltest.c 183: }
c:\unimel\kalman\kaltest.c 184: kalman_state = 3;
c:\unimel\kalman\kaltest.c 185: break;
c:\unimel\kalman\kaltest.c 186: 
c:\unimel\kalman\kaltest.c 187: default : 	kalman_state = 0;
c:\unimel\kalman\kaltest.c 188: flag = 0;
c:\unimel\kalman\kaltest.c 189: break;
c:\unimel\kalman\kaltest.c 190: }
c:\unimel\kalman\kaltest.c 191: }
c:\unimel\kalman\kaltest.c 192: 
c:\unimel\kalman\kaltest.c 193: main()
c:\unimel\kalman\kaltest.c 194: {
c:\unimel\kalman\kaltest.c 195: atcumode=1;
c:\unimel\kalman\kaltest.c 196: atcustate=0;
c:\unimel\kalman\kaltest.c 197: azcmd=160;
c:\unimel\kalman\kaltest.c 198: azmsd=160;
c:\unimel\kalman\kaltest.c 199: elcmd=25;
c:\unimel\kalman\kaltest.c 200: elmsd=25;
c:\unimel\kalman\kaltest.c 201: 
c:\unimel\kalman\kaltest.c 202: while (atcumode==1) {
c:\unimel\kalman\kaltest.c 203: timer = clock()/1000.0;
c:\unimel\kalman\kaltest.c 204: printf("timer :");
c:\unimel\kalman\kaltest.c 205: printf("%d\n",timer);
c:\unimel\kalman\kaltest.c 206: printf("\n");
c:\unimel\kalman\kaltest.c 207: act_az=az_pos_sat(timer);
c:\unimel\kalman\kaltest.c 208: act_el=el_pos_sat(timer);
c:\unimel\kalman\kaltest.c 209: power=power_calc(act_az,act_el,azmsd,elmsd);
c:\unimel\kalman\kaltest.c 210: printf("                                                         power = ");
c:\unimel\kalman\kaltest.c 211: printf("%.4f\n",power);
c:\unimel\kalman\kaltest.c 212: printf("\n");
c:\unimel\kalman\kaltest.c 213: kalman_sm(&atcustate,&azcmd,&elcmd,&azmsd,&elmsd,&power,atcustate);
c:\unimel\kalman\kaltest.c 214: printf("     atcu state : ");
c:\unimel\kalman\kaltest.c 215: printf("%d\n",atcustate);
c:\unimel\kalman\kaltest.c 216: printf("\n");
c:\unimel\kalman\kaltest.c 217: }
c:\unimel\kalman\kaltest.c 218: return 0 ;
c:\unimel\kalman\kaltest.c 219: }
c:\unimel\kalman\kaltest.c 220: 
c:\unimel\kalman\kaltest.c 221: 